export type Lang = 'en' | 'fr' | 'pt' | 'ar' | 'sw' | 'zh' | 'hi' | 'id' | 'bn' | 'ur' | 'ja' | 'ko';

export const LANGUAGES: { code: Lang; label: string; nativeName: string; flag: string }[] = [
  { code: 'en', label: 'English',    nativeName: 'English',    flag: '🇬🇧' },
  { code: 'fr', label: 'French',     nativeName: 'Français',   flag: '🇫🇷' },
  { code: 'pt', label: 'Portuguese', nativeName: 'Português',  flag: '🇧🇷' },
  { code: 'ar', label: 'Arabic',     nativeName: 'العربية',    flag: '🇸🇦' },
  { code: 'sw', label: 'Swahili',    nativeName: 'Kiswahili',  flag: '🇰🇪' },
  { code: 'zh', label: 'Chinese',    nativeName: '中文',        flag: '🇨🇳' },
  { code: 'hi', label: 'Hindi',      nativeName: 'हिंदी',       flag: '🇮🇳' },
  { code: 'id', label: 'Indonesian', nativeName: 'Bahasa Indonesia', flag: '🇮🇩' },
  { code: 'bn', label: 'Bengali',    nativeName: 'বাংলা',       flag: '🇧🇩' },
  { code: 'ur', label: 'Urdu',       nativeName: 'اردو',        flag: '🇵🇰' },
  { code: 'ja', label: 'Japanese',   nativeName: '日本語',       flag: '🇯🇵' },
  { code: 'ko', label: 'Korean',     nativeName: '한국어',       flag: '🇰🇷' },
];

export const RTL_LANGS = new Set<string>(['ar', 'ur']);

function t(map: Partial<Record<Lang, string>>, lang: string): string {
  return map[lang as Lang] ?? map['en'] ?? '';
}

type TranslationMap = Partial<Record<Lang, string>>;

const T: Record<string, TranslationMap> = {
  // ── Navigation ─────────────────────────────────────────────────────────────
  home: { en:'Home', fr:'Accueil', pt:'Início', ar:'الرئيسية', sw:'Nyumbani', zh:'首页', hi:'होम', id:'Beranda', bn:'হোম', ur:'ہوم', ja:'ホーム', ko:'홈' },
  listings: { en:'All Listings', fr:'Annonces', pt:'Anúncios', ar:'الإعلانات', sw:'Matangazo', zh:'所有列表', hi:'सभी लिस्टिंग', id:'Semua Listing', bn:'সব তালিকা', ur:'تمام اشتہارات', ja:'全リスト', ko:'전체 목록' },
  sellers: { en:'Sellers', fr:'Vendeurs', pt:'Vendedores', ar:'البائعون', sw:'Wauzaji', zh:'卖家', hi:'विक्रेता', id:'Penjual', bn:'বিক্রেতা', ur:'فروخت کنندگان', ja:'出品者', ko:'판매자' },
  happenings: { en:'Happenings', fr:'Événements', pt:'Acontecimentos', ar:'الأحداث', sw:'Matukio', zh:'活动', hi:'इवेंट', id:'Acara', bn:'ঘটনাবলী', ur:'واقعات', ja:'イベント', ko:'이벤트' },
  flashSales: { en:'Flash Sales', fr:'Ventes Flash', pt:'Vendas Relâmpago', ar:'عروض خاطفة', sw:'Mauzo ya Haraka', zh:'闪购', hi:'फ्लैश सेल', id:'Flash Sale', bn:'ফ্ল্যাশ সেল', ur:'فلیش سیل', ja:'フラッシュセール', ko:'플래시 세일' },
  blog: { en:'Blog', fr:'Blog', pt:'Blog', ar:'المدونة', sw:'Blogu', zh:'博客', hi:'ब्लॉग', id:'Blog', bn:'ব্লগ', ur:'بلاگ', ja:'ブログ', ko:'블로그' },
  categories: { en:'Categories', fr:'Catégories', pt:'Categorias', ar:'الفئات', sw:'Makundi', zh:'分类', hi:'श्रेणियाँ', id:'Kategori', bn:'বিভাগ', ur:'زمرے', ja:'カテゴリー', ko:'카테고리' },
  messages: { en:'Messages', fr:'Messages', pt:'Mensagens', ar:'الرسائل', sw:'Ujumbe', zh:'消息', hi:'संदेश', id:'Pesan', bn:'বার্তা', ur:'پیغامات', ja:'メッセージ', ko:'메시지' },
  saved: { en:'Saved', fr:'Sauvegardé', pt:'Salvos', ar:'المحفوظات', sw:'Zilizohifadhiwa', zh:'收藏', hi:'सहेजे गए', id:'Tersimpan', bn:'সংরক্ষিত', ur:'محفوظ', ja:'保存済み', ko:'저장됨' },
  savedListings: { en:'Saved Listings', fr:'Annonces sauvegardées', pt:'Anúncios salvos', ar:'الإعلانات المحفوظة', sw:'Matangazo Yaliyohifadhiwa', zh:'收藏的商品', hi:'सहेजी गई लिस्टिंग', id:'Listing Tersimpan', bn:'সংরক্ষিত তালিকা', ur:'محفوظ فہرستیں', ja:'保存済みリスト', ko:'저장된 목록' },
  howItWorks: { en:'How It Works', fr:'Comment ça marche', pt:'Como funciona', ar:'كيف يعمل', sw:'Jinsi Inavyofanya Kazi', zh:'如何使用', hi:'यह कैसे काम करता है', id:'Cara Kerja', bn:'কিভাবে কাজ করে', ur:'یہ کیسے کام کرتا ہے', ja:'使い方', ko:'사용 방법' },
  howItWorksLabel:    { en:'How it works' },
  howItWorksTitle:    { en:'Simple. Powerful. Global.' },
  howItWorksSubtitle: { en:'From discovery to deal — SYPH makes every step effortless.' },
  howItWorksLinkLabel:{ en:'Learn more about SYPH' },
  howStep1Title: { en:'Get location specific results by country/region' },
  howStep1Desc:  { en:'Browse listings filtered to your exact country or region — see only what\'s available near you.' },
  howStep2Title: { en:'Get in contact with your specified service provider/seller' },
  howStep2Desc:  { en:'Message sellers directly through the platform. Ask questions and build trust before you commit.' },
  howStep3Title: { en:'Negotiate your way to a successful deal' },
  howStep3Desc:  { en:'Close the deal on your own terms — negotiate price, arrange pickup or delivery, and buy with confidence.' },
  signIn: { en:'Sign In', fr:'Se connecter', pt:'Entrar', ar:'تسجيل الدخول', sw:'Ingia', zh:'登录', hi:'साइन इन', id:'Masuk', bn:'সাইন ইন', ur:'سائن ان', ja:'サインイン', ko:'로그인' },
  signInSignUp: { en:'Sign In / Sign Up', fr:'Se connecter / S\'inscrire', pt:'Entrar / Cadastrar', ar:'تسجيل الدخول / إنشاء حساب', sw:'Ingia / Jisajili', zh:'登录 / 注册', hi:'साइन इन / साइन अप', id:'Masuk / Daftar', bn:'সাইন ইন / সাইন আপ', ur:'سائن ان / سائن اپ', ja:'サインイン / 登録', ko:'로그인 / 가입' },
  signOut: { en:'Sign Out', fr:'Déconnexion', pt:'Sair', ar:'تسجيل الخروج', sw:'Ondoka', zh:'退出登录', hi:'साइन आउट', id:'Keluar', bn:'সাইন আউট', ur:'سائن آؤٹ', ja:'サインアウト', ko:'로그아웃' },
  sell: { en:'+ Sell', fr:'+ Vendre', pt:'+ Vender', ar:'+ بيع', sw:'+ Uza', zh:'+ 出售', hi:'+ बेचें', id:'+ Jual', bn:'+ বিক্রি', ur:'+ بیچیں', ja:'+ 出品', ko:'+ 판매' },
  startSelling: { en:'+ Start Selling', fr:'+ Commencer à vendre', pt:'+ Começar a vender', ar:'+ ابدأ البيع', sw:'+ Anza Kuuza', zh:'+ 开始出售', hi:'+ बेचना शुरू करें', id:'+ Mulai Berjualan', bn:'+ বিক্রি শুরু করুন', ur:'+ بیچنا شروع کریں', ja:'+ 出品を始める', ko:'+ 판매 시작' },
  signedOut: { en:'Signed out', fr:'Déconnecté', pt:'Saiu da conta', ar:'تم تسجيل الخروج', sw:'Umetoka', zh:'已退出', hi:'साइन आउट हो गए', id:'Keluar', bn:'সাইন আউট হয়েছে', ur:'سائن آؤٹ ہو گئے', ja:'サインアウトしました', ko:'로그아웃되었습니다' },
  language: { en:'Language', fr:'Langue', pt:'Idioma', ar:'اللغة', sw:'Lugha', zh:'语言', hi:'भाषा', id:'Bahasa', bn:'ভাষা', ur:'زبان', ja:'言語', ko:'언어' },
  currency: { en:'Currency', fr:'Devise', pt:'Moeda', ar:'العملة', sw:'Sarafu', zh:'货币', hi:'मुद्रा', id:'Mata Uang', bn:'মুদ্রা', ur:'کرنسی', ja:'通貨', ko:'통화' },
  displayCurrency: { en:'Display Currency', fr:"Devise d'affichage", pt:'Moeda de exibição', ar:'عملة العرض', sw:'Sarafu ya Onyesho', zh:'显示货币', hi:'प्रदर्शन मुद्रा', id:'Mata Uang Tampilan', bn:'প্রদর্শন মুদ্রা', ur:'ڈسپلے کرنسی', ja:'表示通貨', ko:'표시 통화' },
  selectLanguage: { en:'Select Language', fr:'Choisir la langue', pt:'Selecionar idioma', ar:'اختر اللغة', sw:'Chagua Lugha', zh:'选择语言', hi:'भाषा चुनें', id:'Pilih Bahasa', bn:'ভাষা নির্বাচন করুন', ur:'زبان منتخب کریں', ja:'言語を選択', ko:'언어 선택' },

  // ── Search ─────────────────────────────────────────────────────────────────
  searchHint: { en:'Search listings, sellers, locations...', fr:'Rechercher annonces, vendeurs, lieux...', pt:'Buscar anúncios, vendedores, locais...', ar:'ابحث عن إعلانات، بائعين، مواقع...', sw:'Tafuta matangazo, wauzaji, maeneo...', zh:'搜索商品、卖家、地点...', hi:'लिस्टिंग, विक्रेता, स्थान खोजें...', id:'Cari listing, penjual, lokasi...', bn:'তালিকা, বিক্রেতা, স্থান খুঁজুন...', ur:'فہرستیں، فروخت کنندگان، مقامات تلاش کریں...', ja:'リスト・出品者・場所を検索...', ko:'목록, 판매자, 위치 검색...' },
  search: { en:'Search', fr:'Rechercher', pt:'Pesquisar', ar:'بحث', sw:'Tafuta', zh:'搜索', hi:'खोजें', id:'Cari', bn:'খুঁজুন', ur:'تلاش کریں', ja:'検索', ko:'검색' },
  allCountries: { en:'All countries', fr:'Tous les pays', pt:'Todos os países', ar:'جميع الدول', sw:'Nchi zote', zh:'所有国家', hi:'सभी देश', id:'Semua negara', bn:'সব দেশ', ur:'تمام ممالک', ja:'全ての国', ko:'모든 국가' },

  // ── Home sections ───────────────────────────────────────────────────────────
  seeAll: { en:'See all', fr:'Voir tout', pt:'Ver tudo', ar:'عرض الكل', sw:'Ona yote', zh:'查看全部', hi:'सभी देखें', id:'Lihat semua', bn:'সব দেখুন', ur:'سب دیکھیں', ja:'すべて見る', ko:'전체 보기' },
  trendingNearYou: { en:'Trending Near You', fr:'Tendances près de vous', pt:'Em Alta perto de você', ar:'الرائج بالقرب منك', sw:'Yanayopendelewa Karibu Nawe', zh:'附近热门', hi:'आपके पास ट्रेंडिंग', id:'Trending di Dekat Anda', bn:'আপনার কাছে ট্রেন্ডিং', ur:'آپ کے قریب مقبول', ja:'あなたの近くのトレンド', ko:'내 근처 인기' },
  hotNow: { en:'Hot now', fr:'Populaire', pt:'Em alta', ar:'رائج الآن', sw:'Moto sasa', zh:'热门', hi:'अभी हॉट', id:'Populer', bn:'এখন জনপ্রিয়', ur:'ابھی مقبول', ja:'注目', ko:'지금 인기' },
  newest: { en:'Newest', fr:'Plus récent', pt:'Mais recente', ar:'الأحدث', sw:'Mpya zaidi', zh:'最新', hi:'नवीनतम', id:'Terbaru', bn:'নতুনতম', ur:'نئے ترین', ja:'新着順', ko:'최신순' },
  newestListings: { en:'Newest Listings', fr:'Nouvelles annonces', pt:'Anúncios mais recentes', ar:'أحدث الإعلانات', sw:'Matangazo Mapya', zh:'最新列表', hi:'नई लिस्टिंग', id:'Listing Terbaru', bn:'নতুন তালিকা', ur:'نئی فہرستیں', ja:'新着リスト', ko:'최신 목록' },
  flashSalesEndingSoon: { en:'Flash Sales · Ending Soon', fr:'Ventes Flash · Bientôt terminé', pt:'Flash Sales · Encerrando em Breve', ar:'عروض خاطفة · تنتهي قريباً', sw:'Mauzo ya Haraka · Yanakwisha Hivi Karibuni', zh:'闪购 · 即将结束', hi:'फ्लैश सेल · जल्द समाप्त', id:'Flash Sale · Segera Berakhir', bn:'ফ্ল্যাশ সেল · শীঘ্রই শেষ', ur:'فلیش سیل · جلد ختم', ja:'フラッシュセール · 間もなく終了', ko:'플래시 세일 · 곧 종료' },
  endsIn: { en:'Ends in', fr:'Se termine dans', pt:'Termina em', ar:'ينتهي في', sw:'Inaisha baada ya', zh:'结束于', hi:'समाप्त होता है', id:'Berakhir dalam', bn:'শেষ হবে', ur:'ختم ہوتا ہے', ja:'終了まで', ko:'종료까지' },
  sponsored: { en:'Sponsored', fr:'Sponsorisé', pt:'Patrocinado', ar:'ممول', sw:'Iliyosponsor', zh:'赞助', hi:'प्रायोजित', id:'Disponsori', bn:'স্পনসর করা', ur:'سپانسر شدہ', ja:'スポンサー', ko:'광고' },
  browseCategories: { en:'Browse Categories', fr:'Parcourir les catégories', pt:'Navegar por categorias', ar:'تصفح الفئات', sw:'Vinjari makundi', zh:'浏览分类', hi:'श्रेणियाँ देखें', id:'Jelajahi Kategori', bn:'বিভাগ দেখুন', ur:'زمرے دیکھیں', ja:'カテゴリを見る', ko:'카테고리 보기' },
  happeningsNearYou: { en:'Happenings Near You', fr:'Événements près de vous', pt:'Eventos perto de você', ar:'الأحداث بالقرب منك', sw:'Matukio Karibu Nawe', zh:'附近活动', hi:'आपके पास के इवेंट', id:'Acara di Dekat Anda', bn:'আপনার কাছে ঘটনাবলী', ur:'آپ کے قریب واقعات', ja:'あなたの近くのイベント', ko:'내 근처 이벤트' },
  sponsoredContent: { en:'Sponsored Content', fr:'Contenu sponsorisé', pt:'Conteúdo patrocinado', ar:'محتوى ممول', sw:'Maudhui Yaliyosponsor', zh:'赞助内容', hi:'प्रायोजित सामग्री', id:'Konten Disponsori', bn:'স্পনসর করা বিষয়বস্তু', ur:'سپانسر شدہ مواد', ja:'スポンサーコンテンツ', ko:'스폰서 콘텐츠' },
  noListingsYet: { en:'No listings yet', fr:'Pas encore d\'annonces', pt:'Sem anúncios ainda', ar:'لا توجد إعلانات بعد', sw:'Bado hakuna matangazo', zh:'暂无列表', hi:'अभी कोई लिस्टिंग नहीं', id:'Belum ada listing', bn:'এখনো কোনো তালিকা নেই', ur:'ابھی کوئی فہرست نہیں', ja:'まだリストがありません', ko:'아직 목록이 없습니다' },

  // ── Hero tagline ────────────────────────────────────────────────────────────
  tagline: { en:'Find it. Locate it. Connect.', fr:'Trouvez. Localisez. Connectez.', pt:'Encontre. Localize. Conecte.', ar:'اكتشف. حدد موقعه. تواصل.', sw:'Tafuta. Pata. Unganika.', zh:'发现。定位。连接。', hi:'खोजें। जानें। जुड़ें।', id:'Temukan. Lacak. Hubungkan.', bn:'খুঁজুন। সন্ধান করুন। যুক্ত হন।', ur:'تلاش کریں۔ جانیں۔ جڑیں۔', ja:'見つける。定位する。つながる。', ko:'찾아보세요. 확인하세요. 연결하세요.' },
  taglineDesc: { en:'Discover products, services, and happenings near you.', fr:'Découvrez des produits, services et événements près de chez vous.', pt:'Descubra produtos, serviços e acontecimentos perto de você.', ar:'اكتشف المنتجات والخدمات والأحداث بالقرب منك.', sw:'Gundua bidhaa, huduma, na matukio karibu nawe.', zh:'发现您附近的商品、服务和活动。', hi:'आपके पास के उत्पाद, सेवाएँ और इवेंट खोजें।', id:'Temukan produk, layanan, dan acara di sekitar Anda.', bn:'আপনার কাছের পণ্য, পরিষেবা এবং ঘটনা আবিষ্কার করুন।', ur:'اپنے قریب کی مصنوعات، خدمات اور واقعات دریافت کریں۔', ja:'あなたの近くの商品、サービス、イベントを見つけましょう。', ko:'근처의 제품, 서비스, 이벤트를 찾아보세요.' },

  // ── Listing card badges ──────────────────────────────────────────────────────
  openNow: { en:'Open', fr:'Ouvert', pt:'Aberto', ar:'مفتوح', sw:'Wazi', zh:'营业中', hi:'खुला', id:'Buka', bn:'খোলা', ur:'کھلا', ja:'営業中', ko:'영업 중' },
  negotiable: { en:'Negotiable', fr:'Négociable', pt:'Negociável', ar:'قابل للتفاوض', sw:'Inaweza kujadiliwa', zh:'可议价', hi:'बातचीत योग्य', id:'Bisa nego', bn:'আলোচনাযোগ্য', ur:'قابل گفتگو', ja:'価格交渉可', ko:'가격 협상 가능' },
  happening: { en:'Happening', fr:'Événement', pt:'Evento', ar:'حدث', sw:'Tukio', zh:'活动', hi:'इवेंट', id:'Acara', bn:'ঘটনা', ur:'واقعہ', ja:'イベント', ko:'이벤트' },
  save: { en:'Save', fr:'Sauvegarder', pt:'Salvar', ar:'حفظ', sw:'Hifadhi', zh:'收藏', hi:'सहेजें', id:'Simpan', bn:'সংরক্ষণ', ur:'محفوظ', ja:'保存', ko:'저장' },
  unsave: { en:'Unsave', fr:'Retirer', pt:'Remover', ar:'إزالة', sw:'Ondoa', zh:'取消收藏', hi:'हटाएं', id:'Hapus', bn:'সরান', ur:'ہٹائیں', ja:'保存解除', ko:'저장 해제' },

  // ── Auth ────────────────────────────────────────────────────────────────────
  signInToContinue: { en:'Sign in to continue', fr:'Connectez-vous pour continuer', pt:'Entre para continuar', ar:'سجّل الدخول للمتابعة', sw:'Ingia kuendelea', zh:'登录以继续', hi:'जारी रखने के लिए साइन इन करें', id:'Masuk untuk melanjutkan', bn:'চালিয়ে যেতে সাইন ইন করুন', ur:'جاری رکھنے کے لیے سائن ان کریں', ja:'続けるにはサインインしてください', ko:'계속하려면 로그인하세요' },
  featureRegisteredOnly: { en:'This feature is available to registered users only.', fr:'Cette fonctionnalité est réservée aux utilisateurs inscrits.', pt:'Este recurso está disponível apenas para usuários registrados.', ar:'هذه الميزة متاحة للمستخدمين المسجلين فقط.', sw:'Kipengele hiki kinapatikana kwa watumiaji waliojisajili tu.', zh:'此功能仅适用于注册用户。', hi:'यह सुविधा केवल पंजीकृत उपयोगकर्ताओं के लिए है।', id:'Fitur ini hanya tersedia untuk pengguna terdaftar.', bn:'এই বৈশিষ্ট্যটি শুধুমাত্র নিবন্ধিত ব্যবহারকারীদের জন্য।', ur:'یہ فیچر صرف رجسٹرڈ صارفین کے لیے ہے۔', ja:'この機能は登録ユーザーのみ利用可能です。', ko:'이 기능은 등록된 사용자만 사용할 수 있습니다.' },
  loginRequired: { en:'Login required', fr:'Connexion requise', pt:'Login necessário', ar:'تسجيل الدخول مطلوب', sw:'Kuingia kunahitajika', zh:'需要登录', hi:'लॉगिन आवश्यक है', id:'Perlu login', bn:'লগইন প্রয়োজন', ur:'لاگ ان ضروری ہے', ja:'ログインが必要です', ko:'로그인이 필요합니다' },
  loginRequiredDesc: { en:'This feature needs an account. Login or create one to continue.', fr:'Cette fonctionnalité nécessite un compte. Connectez-vous ou créez-en un.', pt:'Este recurso requer uma conta. Faça login ou crie uma.', ar:'هذه الميزة تحتاج حساباً. سجّل الدخول أو أنشئ حساباً.', sw:'Kipengele hiki kinahitaji akaunti. Ingia au unda moja.', zh:'此功能需要账户。请登录或创建账户。', hi:'इस सुविधा के लिए अकाउंट चाहिए। लॉगिन करें या बनाएं।', id:'Fitur ini memerlukan akun. Login atau buat akun.', bn:'এই বৈশিষ্ট্যের জন্য অ্যাকাউন্ট দরকার। লগইন বা তৈরি করুন।', ur:'اس فیچر کے لیے اکاؤنٹ چاہیے۔ لاگ ان کریں یا بنائیں۔', ja:'この機能にはアカウントが必要です。ログインまたは作成してください。', ko:'이 기능은 계정이 필요합니다. 로그인하거나 만드세요.' },
  login: { en:'Login', fr:'Connexion', pt:'Entrar', ar:'تسجيل الدخول', sw:'Ingia', zh:'登录', hi:'लॉगिन', id:'Masuk', bn:'লগইন', ur:'لاگ ان', ja:'ログイン', ko:'로그인' },
  createAccount: { en:'Create account', fr:'Créer un compte', pt:'Criar conta', ar:'إنشاء حساب', sw:'Fungua akaunti', zh:'创建账户', hi:'अकाउंट बनाएं', id:'Buat akun', bn:'অ্যাকাউন্ট তৈরি করুন', ur:'اکاؤنٹ بنائیں', ja:'アカウント作成', ko:'계정 만들기' },
  signUp: { en:'Sign up', fr:"S'inscrire", pt:'Cadastrar', ar:'إنشاء حساب', sw:'Jisajili', zh:'注册', hi:'साइन अप', id:'Daftar', bn:'সাইন আপ', ur:'سائن اپ', ja:'サインアップ', ko:'회원가입' },
  dontHaveAccount: { en:"Don't have an account?", fr:'Pas encore de compte?', pt:'Não tem uma conta?', ar:'ليس لديك حساب؟', sw:'Huna akaunti?', zh:'还没有账户？', hi:'अकाउंट नहीं है?', id:'Belum punya akun?', bn:'অ্যাকাউন্ট নেই?', ur:'اکاؤنٹ نہیں ہے؟', ja:'アカウントをお持ちでないですか？', ko:'계정이 없으신가요?' },
  alreadyHaveAccount: { en:'Already have an account?', fr:'Vous avez déjà un compte?', pt:'Já tem uma conta?', ar:'لديك حساب بالفعل؟', sw:'Una akaunti tayari?', zh:'已经有账户？', hi:'पहले से अकाउंट है?', id:'Sudah punya akun?', bn:'ইতিমধ্যে অ্যাকাউন্ট আছে?', ur:'پہلے سے اکاؤنٹ ہے؟', ja:'すでにアカウントをお持ちですか？', ko:'이미 계정이 있으신가요?' },
  emailField: { en:'Email address', fr:'Adresse e-mail', pt:'Endereço de e-mail', ar:'البريد الإلكتروني', sw:'Barua pepe', zh:'邮箱地址', hi:'ईमेल पता', id:'Alamat email', bn:'ইমেইল ঠিকানা', ur:'ای میل پتہ', ja:'メールアドレス', ko:'이메일 주소' },
  passwordField: { en:'Password', fr:'Mot de passe', pt:'Senha', ar:'كلمة المرور', sw:'Nywila', zh:'密码', hi:'पासवर्ड', id:'Kata sandi', bn:'পাসওয়ার্ড', ur:'پاس ورڈ', ja:'パスワード', ko:'비밀번호' },
  forgotPassword: { en:'Forgot password?', fr:'Mot de passe oublié?', pt:'Esqueceu a senha?', ar:'نسيت كلمة المرور؟', sw:'Umesahau nywila?', zh:'忘记密码？', hi:'पासवर्ड भूल गए?', id:'Lupa kata sandi?', bn:'পাসওয়ার্ড ভুলে গেছেন?', ur:'پاس ورڈ بھول گئے؟', ja:'パスワードをお忘れですか？', ko:'비밀번호를 잊으셨나요?' },
  fullName: { en:'Full name', fr:'Nom complet', pt:'Nome completo', ar:'الاسم الكامل', sw:'Jina kamili', zh:'全名', hi:'पूरा नाम', id:'Nama lengkap', bn:'পুরো নাম', ur:'پورا نام', ja:'フルネーム', ko:'전체 이름' },
  orContinueWith: { en:'Or continue with', fr:'Ou continuer avec', pt:'Ou continuar com', ar:'أو تابع مع', sw:'Au endelea na', zh:'或用以下方式', hi:'या इससे जारी रखें', id:'Atau lanjut dengan', bn:'বা এর সাথে চালিয়ে যান', ur:'یا اس کے ساتھ جاری رکھیں', ja:'または続ける', ko:'또는 다음으로 계속' },
  continueWithGoogle: { en:'Continue with Google', fr:'Continuer avec Google', pt:'Continuar com Google', ar:'المتابعة مع Google', sw:'Endelea na Google', zh:'使用Google继续', hi:'Google से जारी रखें', id:'Lanjutkan dengan Google', bn:'Google দিয়ে চালিয়ে যান', ur:'Google کے ساتھ جاری رکھیں', ja:'Googleで続ける', ko:'Google로 계속하기' },
  notNow: { en:'Not now', fr:'Pas maintenant', pt:'Agora não', ar:'ليس الآن', sw:'Si sasa', zh:'暂不', hi:'अभी नहीं', id:'Tidak sekarang', bn:'এখন না', ur:'ابھی نہیں', ja:'後で', ko:'나중에' },

  // ── Messaging ───────────────────────────────────────────────────────────────
  sendMessage: { en:'Send Message', fr:'Envoyer un message', pt:'Enviar mensagem', ar:'إرسال رسالة', sw:'Tuma Ujumbe', zh:'发送消息', hi:'संदेश भेजें', id:'Kirim Pesan', bn:'বার্তা পাঠান', ur:'پیغام بھیجیں', ja:'メッセージを送る', ko:'메시지 보내기' },
  yourMessage: { en:'Your message...', fr:'Votre message...', pt:'Sua mensagem...', ar:'رسالتك...', sw:'Ujumbe wako...', zh:'您的消息...', hi:'आपका संदेश...', id:'Pesan Anda...', bn:'আপনার বার্তা...', ur:'آپ کا پیغام...', ja:'メッセージを入力...', ko:'메시지를 입력하세요...' },
  send: { en:'Send', fr:'Envoyer', pt:'Enviar', ar:'إرسال', sw:'Tuma', zh:'发送', hi:'भेजें', id:'Kirim', bn:'পাঠান', ur:'بھیجیں', ja:'送る', ko:'보내기' },
  messageSent: { en:'Message sent!', fr:'Message envoyé!', pt:'Mensagem enviada!', ar:'تم إرسال الرسالة!', sw:'Ujumbe umetumwa!', zh:'消息已发送！', hi:'संदेश भेज दिया!', id:'Pesan terkirim!', bn:'বার্তা পাঠানো হয়েছে!', ur:'پیغام بھیج دیا گیا!', ja:'メッセージを送信しました！', ko:'메시지가 전송되었습니다!' },
  messageContact: { en:'Message', fr:'Contacter', pt:'Mensagem', ar:'رسالة', sw:'Ujumbe', zh:'消息', hi:'संदेश', id:'Pesan', bn:'বার্তা', ur:'پیغام', ja:'メッセージ', ko:'메시지' },

  // ── Listing detail ──────────────────────────────────────────────────────────
  contactSeller: { en:'Contact Seller', fr:'Contacter le vendeur', pt:'Contactar vendedor', ar:'تواصل مع البائع', sw:'Wasiliana na Muuzaji', zh:'联系卖家', hi:'विक्रेता से संपर्क करें', id:'Hubungi Penjual', bn:'বিক্রেতার সাথে যোগাযোগ', ur:'بائع سے رابطہ کریں', ja:'出品者に連絡', ko:'판매자 연락' },
  callSeller: { en:'Call Seller', fr:'Appeler le vendeur', pt:'Ligar para vendedor', ar:'اتصل بالبائع', sw:'Piga simu Muuzaji', zh:'致电卖家', hi:'विक्रेता को कॉल करें', id:'Telepon Penjual', bn:'বিক্রেতাকে কল করুন', ur:'بائع کو کال کریں', ja:'出品者に電話', ko:'판매자 전화' },
  shareItem: { en:'Share', fr:'Partager', pt:'Compartilhar', ar:'مشاركة', sw:'Shiriki', zh:'分享', hi:'शेयर', id:'Bagikan', bn:'শেয়ার করুন', ur:'شیئر کریں', ja:'シェア', ko:'공유' },
  description: { en:'Description', fr:'Description', pt:'Descrição', ar:'الوصف', sw:'Maelezo', zh:'描述', hi:'विवरण', id:'Deskripsi', bn:'বিবরণ', ur:'تفصیل', ja:'説明', ko:'설명' },
  details: { en:'Details', fr:'Détails', pt:'Detalhes', ar:'التفاصيل', sw:'Maelezo', zh:'详情', hi:'विवरण', id:'Detail', bn:'বিস্তারিত', ur:'تفصیلات', ja:'詳細', ko:'세부 정보' },
  location: { en:'Location', fr:'Localisation', pt:'Localização', ar:'الموقع', sw:'Mahali', zh:'位置', hi:'स्थान', id:'Lokasi', bn:'অবস্থান', ur:'مقام', ja:'場所', ko:'위치' },
  sellerInfo: { en:'Seller Info', fr:'Info vendeur', pt:'Info do vendedor', ar:'معلومات البائع', sw:'Taarifa za Muuzaji', zh:'卖家信息', hi:'विक्रेता की जानकारी', id:'Info Penjual', bn:'বিক্রেতার তথ্য', ur:'بائع کی معلومات', ja:'出品者情報', ko:'판매자 정보' },
  viewShop: { en:'View Shop', fr:'Voir la boutique', pt:'Ver loja', ar:'عرض المتجر', sw:'Tazama Duka', zh:'查看店铺', hi:'दुकान देखें', id:'Lihat Toko', bn:'দোকান দেখুন', ur:'دکان دیکھیں', ja:'ショップを見る', ko:'가게 보기' },
  reportListing: { en:'Report listing', fr:'Signaler l\'annonce', pt:'Denunciar anúncio', ar:'الإبلاغ عن الإعلان', sw:'Ripoti tangazo', zh:'举报', hi:'रिपोर्ट करें', id:'Laporkan', bn:'রিপোর্ট করুন', ur:'رپورٹ کریں', ja:'報告する', ko:'신고하기' },
  reviews: { en:'Reviews', fr:'Avis', pt:'Avaliações', ar:'المراجعات', sw:'Maoni', zh:'评价', hi:'समीक्षाएँ', id:'Ulasan', bn:'পর্যালোচনা', ur:'جائزے', ja:'レビュー', ko:'리뷰' },
  noReviewsYet: { en:'No reviews yet', fr:'Pas encore d\'avis', pt:'Sem avaliações ainda', ar:'لا توجد مراجعات بعد', sw:'Bado hakuna maoni', zh:'暂无评价', hi:'अभी कोई समीक्षा नहीं', id:'Belum ada ulasan', bn:'এখনো কোনো পর্যালোচনা নেই', ur:'ابھی کوئی جائزہ نہیں', ja:'まだレビューがありません', ko:'아직 리뷰가 없습니다' },
  writeReview: { en:'Write a review', fr:'Écrire un avis', pt:'Escrever avaliação', ar:'كتابة مراجعة', sw:'Andika maoni', zh:'写评价', hi:'समीक्षा लिखें', id:'Tulis ulasan', bn:'পর্যালোচনা লিখুন', ur:'جائزہ لکھیں', ja:'レビューを書く', ko:'리뷰 쓰기' },
  condition: { en:'Condition', fr:'État', pt:'Condição', ar:'الحالة', sw:'Hali', zh:'成色', hi:'स्थिति', id:'Kondisi', bn:'অবস্থা', ur:'حالت', ja:'状態', ko:'상태' },
  new: { en:'New', fr:'Neuf', pt:'Novo', ar:'جديد', sw:'Mpya', zh:'全新', hi:'नया', id:'Baru', bn:'নতুন', ur:'نیا', ja:'新品', ko:'새것' },
  used: { en:'Used', fr:'Utilisé', pt:'Usado', ar:'مستعمل', sw:'Imekuwa ikitumika', zh:'二手', hi:'पुराना', id:'Bekas', bn:'পুরানো', ur:'استعمال شدہ', ja:'中古', ko:'중고' },
  priceNotSet: { en:'Price not set', fr:'Prix non défini', pt:'Preço não definido', ar:'السعر غير محدد', sw:'Bei haijawekwa', zh:'价格未设置', hi:'कीमत तय नहीं', id:'Harga belum diset', bn:'মূল্য নির্ধারিত নয়', ur:'قیمت مقرر نہیں', ja:'価格未設定', ko:'가격 미설정' },

  // ── Common ──────────────────────────────────────────────────────────────────
  loading: { en:'Loading...', fr:'Chargement...', pt:'Carregando...', ar:'جاري التحميل...', sw:'Inapakia...', zh:'加载中...', hi:'लोड हो रहा है...', id:'Memuat...', bn:'লোড হচ্ছে...', ur:'لوڈ ہو رہا ہے...', ja:'読み込み中...', ko:'로딩 중...' },
  noResults: { en:'No results found', fr:'Aucun résultat trouvé', pt:'Nenhum resultado encontrado', ar:'لا توجد نتائج', sw:'Hakuna matokeo', zh:'没有找到结果', hi:'कोई परिणाम नहीं मिला', id:'Tidak ada hasil', bn:'কোন ফলাফল পাওয়া যায়নি', ur:'کوئی نتیجہ نہیں ملا', ja:'結果が見つかりません', ko:'결과가 없습니다' },
  cancel: { en:'Cancel', fr:'Annuler', pt:'Cancelar', ar:'إلغاء', sw:'Ghairi', zh:'取消', hi:'रद्द करें', id:'Batal', bn:'বাতিল', ur:'منسوخ', ja:'キャンセル', ko:'취소' },
  done: { en:'Done', fr:'Terminé', pt:'Concluído', ar:'تم', sw:'Imekamilika', zh:'完成', hi:'पूर्ण', id:'Selesai', bn:'সম্পন্ন', ur:'مکمل', ja:'完了', ko:'완료' },
  filters: { en:'Filters', fr:'Filtres', pt:'Filtros', ar:'فلاتر', sw:'Vichujio', zh:'筛选', hi:'फ़िल्टर', id:'Filter', bn:'ফিল্টার', ur:'فلٹر', ja:'フィルター', ko:'필터' },
  allCategories: { en:'All Categories', fr:'Toutes les catégories', pt:'Todas as categorias', ar:'جميع الفئات', sw:'Makundi Yote', zh:'所有分类', hi:'सभी श्रेणियाँ', id:'Semua Kategori', bn:'সব বিভাগ', ur:'تمام زمرے', ja:'全カテゴリ', ko:'전체 카테고리' },
  verified: { en:'Verified', fr:'Vérifié', pt:'Verificado', ar:'موثق', sw:'Imethibitishwa', zh:'已认证', hi:'सत्यापित', id:'Terverifikasi', bn:'যাচাইকৃত', ur:'تصدیق شدہ', ja:'認証済み', ko:'인증됨' },
  memberSince: { en:'Member since', fr:'Membre depuis', pt:'Membro desde', ar:'عضو منذ', sw:'Mwanachama tangu', zh:'会员自', hi:'सदस्य', id:'Anggota sejak', bn:'সদস্য থেকে', ur:'ممبر', ja:'メンバー歴', ko:'가입일' },
  activeListings: { en:'Active Listings', fr:'Annonces actives', pt:'Anúncios ativos', ar:'الإعلانات النشطة', sw:'Matangazo Yanayotumika', zh:'活跃列表', hi:'सक्रिय लिस्टिंग', id:'Listing Aktif', bn:'সক্রিय তালিকা', ur:'فعال فہرستیں', ja:'アクティブリスト', ko:'활성 목록' },

  // ── Footer ──────────────────────────────────────────────────────────────────
  footerTagline: { en:'Your Global Marketplace', fr:'Votre Marketplace Mondiale', pt:'Seu Marketplace Global', ar:'سوقك العالمي', sw:'Soko Lako la Kimataifa', zh:'您的全球市场', hi:'आपका वैश्विक बाज़ार', id:'Marketplace Global Anda', bn:'আপনার বৈশ্বিক মার্কেটপ্লেস', ur:'آپ کا عالمی مارکیٹ پلیس', ja:'あなたのグローバルマーケット', ko:'당신의 글로벌 마켓플레이스' },
  footerDesc: { en:'Buy, sell, and connect with people near you.', fr:'Achetez, vendez et connectez-vous.', pt:'Compre, venda e conecte-se.', ar:'اشترِ وبع وتواصل مع الناس.', sw:'Nunua, uza, na unganike.', zh:'买卖，与附近的人联系。', hi:'खरीदें, बेचें और लोगों से जुड़ें।', id:'Beli, jual, dan terhubung.', bn:'কিনুন, বিক্রি করুন এবং যুক্ত হন।', ur:'خریدیں، بیچیں اور لوگوں سے جڑیں۔', ja:'売買し、周りの人とつながろう。', ko:'사고 팔고 주변 사람들과 연결하세요.' },
  marketplace: { en:'Marketplace', fr:'Marché', pt:'Mercado', ar:'السوق', sw:'Soko', zh:'市场', hi:'बाज़ार', id:'Pasar', bn:'মার্কেট', ur:'مارکیٹ', ja:'マーケット', ko:'마켓' },
  company: { en:'Company', fr:'Entreprise', pt:'Empresa', ar:'الشركة', sw:'Kampuni', zh:'公司', hi:'कंपनी', id:'Perusahaan', bn:'কোম্পানি', ur:'کمپنی', ja:'会社', ko:'회사' },
  downloadApp: { en:'Download App', fr:'Télécharger l\'app', pt:'Baixar o app', ar:'تحميل التطبيق', sw:'Pakua App', zh:'下载App', hi:'ऐप डाउनलोड', id:'Unduh App', bn:'অ্যাপ ডাউনলোড', ur:'ایپ ڈاؤن لوڈ', ja:'アプリをダウンロード', ko:'앱 다운로드' },
  aboutUs: { en:'About Us', fr:'À propos', pt:'Sobre nós', ar:'عنا', sw:'Kuhusu Sisi', zh:'关于我们', hi:'हमारे बारे में', id:'Tentang Kami', bn:'আমাদের সম্পর্কে', ur:'ہمارے بارے میں', ja:'会社概要', ko:'회사 소개' },
  privacyPolicy: { en:'Privacy Policy', fr:'Politique de confidentialité', pt:'Política de privacidade', ar:'سياسة الخصوصية', sw:'Sera ya Faragha', zh:'隐私政策', hi:'गोपनीयता नीति', id:'Kebijakan Privasi', bn:'গোপনীয়তা নীতি', ur:'رازداری کی پالیسی', ja:'プライバシーポリシー', ko:'개인정보 처리방침' },
  termsConditions: { en:'Terms & Conditions', fr:'Termes et conditions', pt:'Termos e condições', ar:'الشروط والأحكام', sw:'Masharti na Hali', zh:'条款和条件', hi:'नियम और शर्तें', id:'Syarat & Ketentuan', bn:'শর্তাবলী', ur:'شرائط و ضوابط', ja:'利用規約', ko:'이용약관' },
  contactUs: { en:'Contact Us', fr:'Contactez-nous', pt:'Fale conosco', ar:'تواصل معنا', sw:'Wasiliana Nasi', zh:'联系我们', hi:'हमसे संपर्क करें', id:'Hubungi Kami', bn:'আমাদের সাথে যোগাযোগ', ur:'ہم سے رابطہ', ja:'お問い合わせ', ko:'문의하기' },
  allRightsReserved: { en:'All rights reserved.', fr:'Tous droits réservés.', pt:'Todos os direitos reservados.', ar:'جميع الحقوق محفوظة.', sw:'Haki zote zimehifadhiwa.', zh:'版权所有。', hi:'सर्वाधिकार सुरक्षित।', id:'Hak cipta dilindungi.', bn:'সর্বস্বত্ব সংরক্ষিত।', ur:'جملہ حقوق محفوظ ہیں۔', ja:'全著作権所有。', ko:'모든 권리 보유.' },
  comingSoon: { en:'Coming Soon', fr:'Bientôt disponible', pt:'Em breve', ar:'قريباً', sw:'Inakuja Hivi Karibuni', zh:'即将推出', hi:'जल्द आ रहा है', id:'Segera Hadir', bn:'শীঘ্রই আসছে', ur:'جلد آ رہا ہے', ja:'近日公開', ko:'곧 출시' },
  appNotAvailableYet: { en:"The app isn't available yet, but it's coming soon!", fr:"L'app n'est pas encore disponible, mais elle arrive bientôt!", pt:'O app ainda não está disponível, mas chega em breve!', ar:'التطبيق غير متاح بعد، لكنه قادم قريباً!', sw:'App bado haipatikani, lakini inakuja hivi karibuni!', zh:'应用程序尚未发布，但即将推出！', hi:'ऐप अभी उपलब्ध नहीं है, लेकिन जल्द आ रहा है!', id:'Aplikasi belum tersedia, tapi segera hadir!', bn:'অ্যাপটি এখনো পাওয়া যাচ্ছে না, তবে শীঘ্রই আসছে!', ur:'ایپ ابھی دستیاب نہیں ہے، لیکن جلد آ رہی ہے!', ja:'アプリはまだリリースされていませんが、もうすぐ登場します！', ko:'아직 앱이 출시되지 않았지만 곧 출시됩니다!' },
  notifyMe: { en:"Notify me when it's ready", fr:'Me notifier quand c\'est prêt', pt:'Me avise quando estiver pronto', ar:'أبلغني عند الإطلاق', sw:'Niarifu itakapokuwa tayari', zh:'准备好后通知我', hi:'तैयार होने पर मुझे बताएं', id:'Beri tahu saya saat siap', bn:'প্রস্তুত হলে জানান', ur:'تیار ہونے پر مجھے بتائیں', ja:'準備ができたら通知する', ko:'준비되면 알림 받기' },

  // ── Seller directory / shop page ────────────────────────────────────────────
  sellerDirectory: { en:'Seller Directory', fr:'Répertoire des vendeurs', pt:'Diretório de vendedores', ar:'دليل البائعين', sw:'Orodha ya Wauzaji', zh:'卖家目录', hi:'विक्रेता निर्देशिका', id:'Direktori Penjual', bn:'বিক্রেতার নির্দেশিকা', ur:'فروخت کنندگان کی فہرست', ja:'出品者一覧', ko:'판매자 목록' },
  searchSellers: { en:'Search sellers by name or description…', fr:'Chercher des vendeurs par nom ou description…', pt:'Buscar vendedores por nome ou descrição…', ar:'ابحث عن البائعين بالاسم أو الوصف…', sw:'Tafuta wauzaji kwa jina au maelezo…', zh:'按名称或描述搜索卖家…', hi:'नाम या विवरण से विक्रेता खोजें…', id:'Cari penjual berdasarkan nama atau deskripsi…', bn:'নাম বা বিবরণ দিয়ে বিক্রেতা খুঁজুন…', ur:'نام یا تفصیل سے فروخت کنندگان تلاش کریں…', ja:'名前や説明で出品者を検索…', ko:'이름이나 설명으로 판매자 검색…' },
  noSellersFound: { en:'No sellers found', fr:'Aucun vendeur trouvé', pt:'Nenhum vendedor encontrado', ar:'لم يتم العثور على بائعين', sw:'Hakuna wauzaji waliopatikana', zh:'没有找到卖家', hi:'कोई विक्रेता नहीं मिला', id:'Tidak ada penjual ditemukan', bn:'কোনো বিক্রেতা পাওয়া যায়নি', ur:'کوئی فروخت کنندہ نہیں ملا', ja:'出品者が見つかりません', ko:'판매자를 찾을 수 없습니다' },
  shopNotFound: { en:'Shop not found', fr:'Boutique introuvable', pt:'Loja não encontrada', ar:'المتجر غير موجود', sw:'Duka halipatikani', zh:'店铺未找到', hi:'दुकान नहीं मिली', id:'Toko tidak ditemukan', bn:'দোকান পাওয়া যায়নি', ur:'دکان نہیں ملی', ja:'ショップが見つかりません', ko:'가게를 찾을 수 없습니다' },

  // ── Hero ────────────────────────────────────────────────────────────────────
  heroBadge: { en:'Your Global Marketplace', fr:'Votre Marketplace Mondiale', pt:'Seu Marketplace Global', ar:'سوقك العالمي', sw:'Soko Lako la Kimataifa', zh:'您的全球市场', hi:'आपका वैश्विक बाज़ार', id:'Marketplace Global Anda', bn:'আপনার বৈশ্বিক মার্কেটপ্লেস', ur:'آپ کا عالمی مارکیٹ پلیس', ja:'あなたのグローバルマーケット', ko:'당신의 글로벌 마켓플레이스' },
  heroFreeToJoin: { en:'Free to join', fr:'Gratuit', pt:'Grátis', ar:'مجاني', sw:'Bure kujiunga', zh:'免费加入', hi:'मुफ्त में जुड़ें', id:'Gratis', bn:'বিনামূল্যে যোগ দিন', ur:'مفت شامل ہوں', ja:'無料参加', ko:'무료 가입' },
  heroHeadline1: { en:'Your Global Broker.', fr:'Votre Courtier Mondial.', pt:'Seu Corretor Global.', ar:'وسيطك العالمي.', sw:'Wakala Wako wa Kimataifa.', zh:'您的全球经纪人。', hi:'आपका वैश्विक दलाल।', id:'Broker Global Anda.', bn:'আপনার গ্লোবাল ব্রোকার।', ur:'آپ کا عالمی بروکر۔', ja:'あなたのグローバルブローカー。', ko:'당신의 글로벌 브로커.' },
  heroHeadline2: { en:'For All Goods & Services.', fr:'Pour Tous Biens & Services.', pt:'Para Todos os Bens & Serviços.', ar:'لكل البضائع والخدمات.', sw:'Kwa Bidhaa & Huduma Zote.', zh:'覆盖所有商品与服务。', hi:'सभी वस्तुओं और सेवाओं के लिए।', id:'Untuk Semua Barang & Jasa.', bn:'সকল পণ্য ও পরিষেবার জন্য।', ur:'تمام اشیاء و خدمات کے لیے۔', ja:'あらゆる商品・サービスのために。', ko:'모든 상품과 서비스를 위해.' },
  heroWord1: { en:'Discover.', fr:'Découvrez.', pt:'Descubra.', ar:'اكتشف.', sw:'Gundua.', zh:'发现。', hi:'खोजें।', id:'Temukan.', bn:'আবিষ্কার করুন।', ur:'دریافت کریں۔', ja:'見つけよう。', ko:'발견하세요.' },
  heroWord2: { en:'Connect.', fr:'Connectez.', pt:'Conecte.', ar:'تواصل.', sw:'Unganika.', zh:'连接。', hi:'जुड़ें।', id:'Terhubung.', bn:'সংযুক্ত হন।', ur:'جڑیں۔', ja:'つながろう。', ko:'연결하세요.' },
  heroWord3: { en:'Sell.', fr:'Vendez.', pt:'Venda.', ar:'بع.', sw:'Uza.', zh:'出售。', hi:'बेचें।', id:'Jual.', bn:'বিক্রি করুন।', ur:'بیچیں۔', ja:'売ろう。', ko:'판매하세요.' },
  heroWord4: { en:'Thrive.', fr:'Prospérez.', pt:'Prospere.', ar:'ازدهر.', sw:'Stawi.', zh:'繁荣。', hi:'फलें-फूलें।', id:'Berkembang.', bn:'সমৃদ্ধ হন।', ur:'ترقی کریں۔', ja:'成長しよう。', ko:'번성하세요.' },
  heroSubtitle: { en:"Connect with verified sellers and service providers across the globe. See who's Open Now — all from one platform.", fr:"Connectez-vous avec des vendeurs vérifiés. Voyez qui est ouvert maintenant.", pt:'Conecte-se com vendedores verificados. Veja quem está aberto agora.', ar:'تواصل مع البائعين الموثقين حول العالم. اعرف من هو مفتوح الآن.', sw:'Unganika na wauzaji waliothibitishwa. Angalia waliofungua sasa.', zh:'与认证卖家联系。查看谁现在营业。', hi:'सत्यापित विक्रेताओं से जुड़ें। देखें कौन अभी खुला है।', id:'Terhubung dengan penjual terverifikasi. Lihat siapa yang buka sekarang.', bn:'যাচাইকৃত বিক্রেতাদের সাথে সংযুক্ত হন। দেখুন কে এখন খোলা আছে।', ur:'تصدیق شدہ بائعوں سے رابطہ کریں۔ دیکھیں کون ابھی کھلا ہے۔', ja:'認証済み出品者と繋がりましょう。今営業中の店を確認できます。', ko:'인증된 판매자와 연결하세요. 지금 영업 중인 곳을 확인하세요.' },
  heroSearchPlaceholder: { en:'Search goods, services, sellers…', fr:'Rechercher biens, services, vendeurs…', pt:'Buscar bens, serviços, vendedores…', ar:'ابحث عن بضائع، خدمات، بائعين…', sw:'Tafuta bidhaa, huduma, wauzaji…', zh:'搜索商品、服务、卖家…', hi:'सामान, सेवाएँ, विक्रेता खोजें…', id:'Cari barang, jasa, penjual…', bn:'পণ্য, সেবা, বিক্রেতা খুঁজুন…', ur:'سامان، خدمات، بائع تلاش کریں…', ja:'商品・サービス・出品者を検索…', ko:'상품, 서비스, 판매자 검색…' },
  heroShowingIn: { en:'Showing listings in', fr:'Résultats dans', pt:'Mostrando anúncios em', ar:'عرض الإعلانات في', sw:'Matangazo katika', zh:'显示结果：', hi:'लिस्टिंग दिखाई जा रही हैं:', id:'Menampilkan listing di', bn:'তালিকা দেখাচ্ছে:', ur:'فہرستیں دکھا رہے ہیں:', ja:'表示中:', ko:'목록 표시 중:' },
  heroTapToClear: { en:'tap × to see all countries', fr:'appuyez × pour voir tous les pays', pt:'toque × para ver todos os países', ar:'اضغط × لرؤية كل الدول', sw:'bonyeza × kuona nchi zote', zh:'点×查看所有国家', hi:'× दबाएं सभी देश देखने के लिए', id:'ketuk × untuk lihat semua negara', bn:'× চাপুন সব দেশ দেখতে', ur:'تمام ممالک دیکھنے کے لیے × دبائیں', ja:'×で全国を表示', ko:'× 눌러 모든 국가 보기' },
  heroAllCategories: { en:'All Categories', fr:'Toutes les catégories', pt:'Todas as categorias', ar:'جميع الفئات', sw:'Makundi Yote', zh:'所有分类', hi:'सभी श्रेणियाँ', id:'Semua Kategori', bn:'সব বিভাগ', ur:'تمام زمرے', ja:'全カテゴリ', ko:'전체 카테고리' },
  heroFreeTrial: { en:'Free Trial', fr:'Essai gratuit', pt:'Teste gratuito', ar:'تجربة مجانية', sw:'Jaribio Bure', zh:'免费试用', hi:'मुफ्त ट्रायल', id:'Uji Coba Gratis', bn:'বিনামূল্যে ট্রায়াল', ur:'مفت ٹرائل', ja:'無料トライアル', ko:'무료 체험' },
  heroCountriesStat: { en:'Countries', fr:'Pays', pt:'Países', ar:'الدول', sw:'Nchi', zh:'国家', hi:'देश', id:'Negara', bn:'দেশ', ur:'ممالک', ja:'国', ko:'국가' },
  heroCategoriesStat: { en:'Categories', fr:'Catégories', pt:'Categorias', ar:'الفئات', sw:'Makundi', zh:'分类', hi:'श्रेणियाँ', id:'Kategori', bn:'বিভাগ', ur:'زمرے', ja:'カテゴリ', ko:'카테고리' },

  // ── Category grid ───────────────────────────────────────────────────────────
  browse: { en:'Browse', fr:'Parcourir', pt:'Navegar', ar:'تصفح', sw:'Vinjari', zh:'浏览', hi:'ब्राउज़', id:'Jelajahi', bn:'ব্রাউজ', ur:'براؤز', ja:'参照', ko:'탐색' },
  allCategoriesHeading: { en:'All Categories', fr:'Toutes les catégories', pt:'Todas as categorias', ar:'جميع الفئات', sw:'Makundi Yote', zh:'所有分类', hi:'सभी श्रेणियाँ', id:'Semua Kategori', bn:'সব বিভাগ', ur:'تمام زمرے', ja:'全カテゴリ', ko:'전체 카테고리' },
  hoverToPreview: { en:'Hover a category to preview subcategories', fr:'Survolez une catégorie pour prévisualiser', pt:'Passe o mouse para visualizar subcategorias', ar:'حرك الماوس لمعاينة الفئات الفرعية', sw:'Elekeza kwenye kikundi kuona makundi madogo', zh:'悬停查看子分类', hi:'सबकेटेगरी देखने के लिए होवर करें', id:'Arahkan kursor untuk pratinjau subkategori', bn:'সাবক্যাটাগরি দেখতে হোভার করুন', ur:'ذیلی زمرے دیکھنے کے لیے ہوور کریں', ja:'ホバーでサブカテゴリを確認', ko:'카테고리에 마우스를 올려 하위 항목 보기' },
  allListingsLink: { en:'All listings', fr:'Toutes les annonces', pt:'Todos os anúncios', ar:'جميع الإعلانات', sw:'Matangazo yote', zh:'所有列表', hi:'सभी लिस्टिंग', id:'Semua listing', bn:'সব তালিকা', ur:'تمام فہرستیں', ja:'全リスト', ko:'전체 목록' },
  typesCount: { en:'types', fr:'types', pt:'tipos', ar:'نوع', sw:'aina', zh:'种类', hi:'प्रकार', id:'tipe', bn:'ধরন', ur:'اقسام', ja:'種類', ko:'유형' },
  andMoreCount: { en:'more', fr:'de plus', pt:'a mais', ar:'المزيد', sw:'zaidi', zh:'更多', hi:'और', id:'lainnya', bn:'আরো', ur:'مزید', ja:'他', ko:'더' },

  // ── Footer ──────────────────────────────────────────────────────────────────
  footerBrandDesc: { en:'Your global marketplace for goods and services. Buy and sell anything, anywhere.', fr:'Votre marketplace mondiale pour biens et services. Achetez et vendez partout.', pt:'Seu marketplace global para bens e serviços. Compre e venda em qualquer lugar.', ar:'سوقك العالمي للبضائع والخدمات. اشترِ وبع في أي مكان.', sw:'Soko lako la kimataifa kwa bidhaa na huduma. Nunua na uza popote.', zh:'您的商品与服务全球市场。随时随地买卖。', hi:'वस्तुओं और सेवाओं के लिए आपका वैश्विक बाज़ार। कहीं भी खरीदें और बेचें।', id:'Marketplace global Anda untuk barang dan jasa. Beli dan jual di mana saja.', bn:'পণ্য ও সেবার জন্য আপনার বৈশ্বিক মার্কেটপ্লেস। যেকোনো জায়গায় কিনুন ও বিক্রি করুন।', ur:'اشیاء اور خدمات کے لیے آپ کا عالمی مارکیٹ پلیس۔ کہیں بھی خریدیں اور بیچیں۔', ja:'商品とサービスのためのグローバルマーケット。どこでも売買できます。', ko:'상품과 서비스를 위한 글로벌 마켓플레이스. 어디서든 사고 파세요.' },
  getTheApp: { en:'Get the App', fr:"Télécharger l'app", pt:'Baixar o app', ar:'تحميل التطبيق', sw:'Pakua App', zh:'下载App', hi:'ऐप डाउनलोड करें', id:'Unduh App', bn:'অ্যাপ ডাউনলোড করুন', ur:'ایپ ڈاؤن لوڈ کریں', ja:'アプリを入手', ko:'앱 받기' },
  footerAppDesc: { en:'Download Syph and start buying or selling in minutes.', fr:'Téléchargez Syph et commencez en quelques minutes.', pt:'Baixe o Syph e comece em minutos.', ar:'حمّل تطبيق Syph وابدأ البيع أو الشراء في دقائق.', sw:'Pakua Syph na uanze kununua au kuuza kwa dakika.', zh:'下载Syph，几分钟内开始买卖。', hi:'Syph डाउनलोड करें और मिनटों में खरीदना या बेचना शुरू करें।', id:'Unduh Syph dan mulai beli atau jual dalam menit.', bn:'Syph ডাউনলোড করুন এবং মিনিটের মধ্যে কেনাকাটা বা বিক্রি শুরু করুন।', ur:'Syph ڈاؤن لوڈ کریں اور منٹوں میں خریدنا یا بیچنا شروع کریں۔', ja:'Syphをダウンロードして数分で売買を開始。', ko:'Syph를 다운로드하여 몇 분 안에 사고 팔기 시작하세요.' },
  newArrivals: { en:'New Arrivals', fr:'Nouveautés', pt:'Novidades', ar:'وصول جديد', sw:'Vitu Vipya', zh:'新品上架', hi:'नए आइटम', id:'Produk Baru', bn:'নতুন আগমন', ur:'نئی آمد', ja:'新着', ko:'신상품' },
  trustSafety: { en:'Trust & Safety', fr:'Confiance & Sécurité', pt:'Confiança e Segurança', ar:'الثقة والأمان', sw:'Uaminifu & Usalama', zh:'信任与安全', hi:'विश्वास और सुरक्षा', id:'Kepercayaan & Keamanan', bn:'বিশ্বাস ও নিরাপত্তা', ur:'اعتماد اور حفاظت', ja:'信頼と安全', ko:'신뢰와 안전' },
  terms: { en:'Terms', fr:'CGU', pt:'Termos', ar:'الشروط', sw:'Masharti', zh:'条款', hi:'नियम', id:'Syarat', bn:'শর্তাবলী', ur:'شرائط', ja:'利用規約', ko:'이용약관' },
  privacy: { en:'Privacy', fr:'Confidentialité', pt:'Privacidade', ar:'الخصوصية', sw:'Faragha', zh:'隐私', hi:'गोपनीयता', id:'Privasi', bn:'গোপনীয়তা', ur:'رازداری', ja:'プライバシー', ko:'개인정보' },
  about: { en:'About', fr:'À propos', pt:'Sobre', ar:'عن', sw:'Kuhusu', zh:'关于', hi:'के बारे में', id:'Tentang', bn:'সম্পর্কে', ur:'کے بارے میں', ja:'概要', ko:'소개' },
  faq: { en:'FAQ', fr:'FAQ', pt:'FAQ', ar:'الأسئلة الشائعة', sw:'Maswali ya Kawaida', zh:'常见问题', hi:'सामान्य प्रश्न', id:'FAQ', bn:'সাধারণ প্রশ্ন', ur:'عمومی سوالات', ja:'よくある質問', ko:'자주 묻는 질문' },

  // ── Listings / Search / Sellers pages ──────────────────────────────────────
  sponsoredListings: { en:'Sponsored Listings', fr:'Annonces sponsorisées', pt:'Anúncios patrocinados', ar:'الإعلانات الممولة', sw:'Matangazo Yaliyosponsor', zh:'赞助列表', hi:'प्रायोजित लिस्टिंग', id:'Listing Disponsori', bn:'স্পনসর করা তালিকা', ur:'سپانسر شدہ فہرستیں', ja:'スポンサーリスト', ko:'스폰서 목록' },
  listingsFound: { en:'listings found', fr:'annonces trouvées', pt:'anúncios encontrados', ar:'إعلانات وجدت', sw:'matangazo yamepatikana', zh:'个列表', hi:'लिस्टिंग मिलीं', id:'listing ditemukan', bn:'তালিকা পাওয়া গেছে', ur:'فہرستیں ملیں', ja:'件のリスト', ko:'개 목록 발견' },
  sellersFound: { en:'sellers found', fr:'vendeurs trouvés', pt:'vendedores encontrados', ar:'بائعون وجدوا', sw:'wauzaji wamepatikana', zh:'个卖家', hi:'विक्रेता मिले', id:'penjual ditemukan', bn:'বিক্রেতা পাওয়া গেছে', ur:'فروخت کنندگان ملے', ja:'人の出品者', ko:'명의 판매자 발견' },
  resultsFound: { en:'results found', fr:'résultats trouvés', pt:'resultados encontrados', ar:'نتائج وجدت', sw:'matokeo yamepatikana', zh:'个结果', hi:'परिणाम मिले', id:'hasil ditemukan', bn:'ফলাফল পাওয়া গেছে', ur:'نتائج ملے', ja:'件の結果', ko:'개 결과 발견' },
  searching: { en:'Searching…', fr:'Recherche…', pt:'Pesquisando…', ar:'جارٍ البحث…', sw:'Inatafuta…', zh:'搜索中…', hi:'खोज रहा है…', id:'Mencari…', bn:'খুঁজছে…', ur:'تلاش ہو رہی ہے…', ja:'検索中…', ko:'검색 중…' },
  resultsFor: { en:'results for', fr:'résultats pour', pt:'resultados para', ar:'نتائج لـ', sw:'matokeo ya', zh:'个结果，关键词', hi:'परिणाम के लिए', id:'hasil untuk', bn:'এর জন্য ফলাফল', ur:'کے نتائج', ja:'件の結果：', ko:'개 결과:' },
  inLocation: { en:'in', fr:'dans', pt:'em', ar:'في', sw:'katika', zh:'在', hi:'में', id:'di', bn:'তে', ur:'میں', ja:'in', ko:'에서' },
  filtersActive: { en:'filter active', fr:'filtre actif', pt:'filtro ativo', ar:'تصفية نشطة', sw:'kichujio kinafanya kazi', zh:'个过滤器', hi:'फ़िल्टर सक्रिय', id:'filter aktif', bn:'ফিল্টার সক্রিয়', ur:'فلٹر فعال', ja:'件のフィルター', ko:'개 필터 적용' },
  filtersActivePlural: { en:'filters active', fr:'filtres actifs', pt:'filtros ativos', ar:'تصفيات نشطة', sw:'vichujio vinavyofanya kazi', zh:'个过滤器已启用', hi:'फ़िल्टर सक्रिय', id:'filter aktif', bn:'ফিল্টার সক্রিয়', ur:'فلٹرز فعال', ja:'件のフィルター適用中', ko:'개 필터 적용 중' },
  startSearching: { en:'Start searching', fr:'Commencer à chercher', pt:'Comece a pesquisar', ar:'ابدأ البحث', sw:'Anza kutafuta', zh:'开始搜索', hi:'खोजना शुरू करें', id:'Mulai mencari', bn:'খোঁজা শুরু করুন', ur:'تلاش شروع کریں', ja:'検索を開始', ko:'검색 시작' },
  typeToFind: { en:'Type above to find listings, sellers, or locations.', fr:'Tapez pour trouver des annonces, vendeurs ou lieux.', pt:'Digite para encontrar anúncios, vendedores ou locais.', ar:'اكتب للعثور على إعلانات أو بائعين أو مواقع.', sw:'Andika kupata matangazo, wauzaji, au maeneo.', zh:'输入以查找列表、卖家或位置。', hi:'लिस्टिंग, विक्रेता या स्थान खोजने के लिए टाइप करें।', id:'Ketik untuk mencari listing, penjual, atau lokasi.', bn:'তালিকা, বিক্রেতা বা স্থান খুঁজতে টাইপ করুন।', ur:'فہرستیں، فروخت کنندگان یا مقامات تلاش کرنے کے لیے ٹائپ کریں۔', ja:'リスト・出品者・場所を検索するには入力してください。', ko:'목록, 판매자, 위치를 찾으려면 입력하세요.' },
  tryRemovingFilters: { en:'Try removing some filters or broadening your search.', fr:'Essayez de supprimer des filtres ou d\'élargir la recherche.', pt:'Tente remover alguns filtros ou ampliar sua pesquisa.', ar:'جرّب إزالة بعض الفلاتر أو توسيع البحث.', sw:'Jaribu kuondoa vichujio au kupanua utafutaji.', zh:'尝试移除一些过滤器或扩大搜索范围。', hi:'कुछ फ़िल्टर हटाएं या खोज को व्यापक करें।', id:'Coba hapus beberapa filter atau perluas pencarian.', bn:'কিছু ফিল্টার সরিয়ে বা অনুসন্ধান বিস্তৃত করুন।', ur:'کچھ فلٹر ہٹانے یا تلاش کو وسیع کرنے کی کوشش کریں۔', ja:'フィルターを削除するか、検索を広げてみてください。', ko:'일부 필터를 제거하거나 검색을 넓혀 보세요.' },
  tryDifferentTerm: { en:'Try a different search term or browse all categories.', fr:'Essayez un autre terme ou parcourez les catégories.', pt:'Tente outro termo ou navegue pelas categorias.', ar:'جرّب مصطلح بحث مختلف أو تصفح جميع الفئات.', sw:'Jaribu neno lingine au vinjari makundi yote.', zh:'尝试不同的搜索词或浏览所有分类。', hi:'अलग सर्च टर्म आज़माएं या सभी श्रेणियाँ देखें।', id:'Coba kata kunci lain atau jelajahi semua kategori.', bn:'ভিন্ন অনুসন্ধান শব্দ ব্যবহার করুন বা সব বিভাগ দেখুন।', ur:'مختلف سرچ ٹرم آزمائیں یا تمام زمرے دیکھیں۔', ja:'別の検索キーワードを試すか、全カテゴリを参照してください。', ko:'다른 검색어를 사용하거나 모든 카테고리를 탐색하세요.' },
  noListingsInCountry: { en:'No listings in', fr:'Pas d\'annonces dans', pt:'Sem anúncios em', ar:'لا توجد إعلانات في', sw:'Hakuna matangazo katika', zh:'没有该地区的列表：', hi:'यहाँ कोई लिस्टिंग नहीं:', id:'Tidak ada listing di', bn:'এ কোনো তালিকা নেই:', ur:'میں کوئی فہرست نہیں:', ja:'のリストはありません:', ko:'의 목록 없음:' },
  tryAdjustingFilters: { en:'Try adjusting your filters or search terms.', fr:'Essayez d\'ajuster vos filtres ou mots-clés.', pt:'Tente ajustar seus filtros ou termos de pesquisa.', ar:'جرّب ضبط الفلاتر أو كلمات البحث.', sw:'Jaribu kurekebisha vichujio au maneno ya utafutaji.', zh:'尝试调整过滤条件或搜索词。', hi:'अपने फ़िल्टर या सर्च टर्म समायोजित करें।', id:'Coba sesuaikan filter atau kata kunci.', bn:'আপনার ফিল্টার বা সার্চ টার্ম পরিবর্তন করুন।', ur:'اپنے فلٹر یا سرچ ٹرم ایڈجسٹ کریں۔', ja:'フィルターや検索キーワードを調整してください。', ko:'필터나 검색어를 조정해 보세요.' },
  verifiedMarketplaceSellers: { en:'Verified Marketplace Sellers', fr:'Vendeurs Vérifiés', pt:'Vendedores Verificados', ar:'بائعو السوق الموثقون', sw:'Wauzaji Waliothibitishwa', zh:'认证卖家', hi:'सत्यापित विक्रेता', id:'Penjual Terverifikasi', bn:'যাচাইকৃত বিক্রেতা', ur:'تصدیق شدہ فروخت کنندگان', ja:'認証済み出品者', ko:'인증된 판매자' },
  sellerDirectoryDesc: { en:'Discover trusted sellers worldwide. Browse by category, country, or search by name.', fr:'Découvrez des vendeurs de confiance dans le monde entier.', pt:'Descubra vendedores confiáveis em todo o mundo.', ar:'اكتشف البائعين الموثوقين في جميع أنحاء العالم.', sw:'Gundua wauzaji wanaoaminika duniani kote.', zh:'在全球范围内发现可信赖的卖家。', hi:'दुनिया भर के विश्वसनीय विक्रेताओं को खोजें।', id:'Temukan penjual terpercaya di seluruh dunia.', bn:'সারা বিশ্বের বিশ্বস্ত বিক্রেতাদের আবিষ্কার করুন।', ur:'دنیا بھر میں قابل اعتماد فروخت کنندگان دریافت کریں۔', ja:'世界中の信頼できる出品者を探しましょう。', ko:'전 세계의 신뢰할 수 있는 판매자를 찾아보세요.' },
  shopNotFoundDesc: { en:"This seller doesn't have a shop yet.", fr:"Ce vendeur n'a pas encore de boutique.", pt:'Este vendedor ainda não tem loja.', ar:'هذا البائع ليس لديه متجر بعد.', sw:'Muuzaji huyu bado hana duka.', zh:'该卖家还没有店铺。', hi:'इस विक्रेता की अभी दुकान नहीं है।', id:'Penjual ini belum punya toko.', bn:'এই বিক্রেতার এখনো কোনো দোকান নেই।', ur:'اس بائع کی ابھی دکان نہیں ہے۔', ja:'この出品者はまだショップがありません。', ko:'이 판매자는 아직 가게가 없습니다.' },
  checkBackSoon: { en:'Check back soon!', fr:'Revenez bientôt!', pt:'Volte em breve!', ar:'عد قريباً!', sw:'Rudi hivi karibuni!', zh:'请稍后再来！', hi:'जल्द वापस देखें!', id:'Kembali lagi nanti!', bn:'শীঘ্রই ফিরে দেখুন!', ur:'جلد واپس آئیں!', ja:'またのご確認をお待ちください！', ko:'곧 다시 확인해 보세요!' },
  noListingsYetShop: { en:"No listings yet", fr:"Pas encore d'annonces", pt:"Sem anúncios ainda", ar:"لا توجد إعلانات بعد", sw:"Bado hakuna matangazo", zh:"暂无列表", hi:"अभी कोई लिस्टिंग नहीं", id:"Belum ada listing", bn:"এখনো কোনো তালিকা নেই", ur:"ابھی کوئی فہرست نہیں", ja:"まだリストがありません", ko:"아직 목록이 없습니다" },

  // ── Home page social proof ──────────────────────────────────────────────────
  trustedByBuyers: { en:'Trusted by buyers and sellers worldwide', fr:'Approuvé par des acheteurs et vendeurs du monde', pt:'Confiado por compradores e vendedores mundiais', ar:'موثوق من المشترين والبائعين حول العالم', sw:'Inayoaminika na wanunuzi na wauzaji duniani', zh:'买家和卖家全球信赖', hi:'दुनिया भर के खरीदारों और विक्रेताओं द्वारा भरोसेमंद', id:'Dipercaya pembeli dan penjual di seluruh dunia', bn:'বিশ্বজুড়ে ক্রেতা ও বিক্রেতাদের বিশ্বস্ত', ur:'دنیا بھر کے خریداروں اور بائعوں کا اعتماد', ja:'世界中の売買に信頼される', ko:'전 세界 구매자와 판매자의 신뢰' },
  buyAndSellOnGo: { en:'Buy & Sell on the Go', fr:'Achetez & Vendez partout', pt:'Compre e Venda em Qualquer Lugar', ar:'اشترِ وبع في أي وقت', sw:'Nunua na Uza Popote', zh:'随时随地买卖', hi:'कहीं भी खरीदें और बेचें', id:'Beli & Jual Di Mana Saja', bn:'যেকোনো জায়গায় কিনুন ও বিক্রি করুন', ur:'کہیں بھی خریدیں اور بیچیں', ja:'どこでも売買', ko:'언제 어디서나 사고 팔기' },
  buyAndSellDesc: { en:'Download the Syph app to list your products, chat with buyers, and manage your business anywhere.', fr:"Téléchargez l'app Syph pour gérer vos ventes n'importe où.", pt:'Baixe o app Syph para gerenciar seu negócio em qualquer lugar.', ar:'حمّل تطبيق Syph لإدارة نشاطك التجاري في أي مكان.', sw:'Pakua app ya Syph kudhibiti biashara yako popote.', zh:'下载Syph应用，随时随地管理您的业务。', hi:'अपने उत्पाद लिस्ट करने और व्यवसाय प्रबंधित करने के लिए Syph ऐप डाउनलोड करें।', id:'Unduh app Syph untuk mengelola bisnis Anda di mana saja.', bn:'পণ্য তালিকাভুক্ত করতে এবং যেকোনো জায়গা থেকে ব্যবসা পরিচালনা করতে Syph অ্যাপ ডাউনলোড করুন।', ur:'اپنی مصنوعات درج کرنے اور کہیں سے بھی کاروبار چلانے کے لیے Syph ایپ ڈاؤن لوڈ کریں۔', ja:'Syphアプリをダウンロードして、どこからでもビジネスを管理しましょう。', ko:'Syph 앱을 다운로드하여 어디서든 상품을 등록하고 비즈니스를 관리하세요.' },

  // ── Filters (advanced) ──────────────────────────────────────────────────────
  minPrice: { en:'Min price', fr:'Prix minimum', pt:'Preço mínimo', ar:'السعر الأدنى', sw:'Bei ya chini', zh:'最低价格', hi:'न्यूनतम मूल्य', id:'Harga minimum', bn:'সর্বনিম্ন মূল্য', ur:'کم از کم قیمت', ja:'最低価格', ko:'최소 가격' },
  maxPrice: { en:'Max price', fr:'Prix maximum', pt:'Preço máximo', ar:'السعر الأقصى', sw:'Bei ya juu', zh:'最高价格', hi:'अधिकतम मूल्य', id:'Harga maksimum', bn:'সর্বোচ্চ মূল্য', ur:'زیادہ سے زیادہ قیمت', ja:'最高価格', ko:'최대 가격' },
  priceRange: { en:'Price range', fr:'Fourchette de prix', pt:'Faixa de preço', ar:'نطاق السعر', sw:'Kiwango cha bei', zh:'价格区间', hi:'मूल्य सीमा', id:'Rentang harga', bn:'মূল্য পরিসীমা', ur:'قیمت کی حد', ja:'価格帯', ko:'가격 범위' },
  timeFilter: { en:'Sort by time', fr:'Trier par date', pt:'Ordenar por tempo', ar:'ترتيب حسب الوقت', sw:'Panga kwa wakati', zh:'按时间排序', hi:'समय से क्रमबद्ध', id:'Urutkan waktu', bn:'সময় অনুসারে বাছাই', ur:'وقت کے حساب سے ترتیب', ja:'日付順', ko:'시간순 정렬' },
  priceFilter: { en:'Sort by price', fr:'Trier par prix', pt:'Ordenar por preço', ar:'ترتيب حسب السعر', sw:'Panga kwa bei', zh:'按价格排序', hi:'कीमत से क्रमबद्ध', id:'Urutkan harga', bn:'মূল্য অনুসারে বাছাই', ur:'قیمت کے حساب سے ترتیب', ja:'価格順', ko:'가격순 정렬' },
  ratingFilter: { en:'Min rating', fr:'Note minimale', pt:'Avaliação mínima', ar:'الحد الأدنى للتقييم', sw:'Ukadiriaji wa chini', zh:'最低评分', hi:'न्यूनतम रेटिंग', id:'Rating minimum', bn:'ন্যূনতম রেটিং', ur:'کم از کم ریٹنگ', ja:'最低評価', ko:'최소 평점' },
  oldest: { en:'Oldest', fr:'Plus ancien', pt:'Mais antigo', ar:'الأقدم', sw:'Kongwe zaidi', zh:'最旧', hi:'पुराने', id:'Terlama', bn:'পুরনো', ur:'پرانے ترین', ja:'古い順', ko:'오래된 순' },
  noneFilter: { en:'None', fr:'Aucun', pt:'Nenhum', ar:'لا شيء', sw:'Hakuna', zh:'无', hi:'कोई नहीं', id:'Tidak ada', bn:'কোনোটি নেই', ur:'کوئی نہیں', ja:'なし', ko:'없음' },
  lowToHigh: { en:'Low → High', fr:'Bas → Haut', pt:'Menor → Maior', ar:'من الأرخص', sw:'Chini → Juu', zh:'低→高', hi:'कम → ज़्यादा', id:'Rendah → Tinggi', bn:'কম → বেশি', ur:'کم → زیادہ', ja:'安い順', ko:'낮은 순' },
  highToLow: { en:'High → Low', fr:'Haut → Bas', pt:'Maior → Menor', ar:'من الأغلى', sw:'Juu → Chini', zh:'高→低', hi:'ज़्यादा → कम', id:'Tinggi → Rendah', bn:'বেশি → কম', ur:'زیادہ → کم', ja:'高い順', ko:'높은 순' },
  anyRating: { en:'Any', fr:'Tout', pt:'Qualquer', ar:'أي', sw:'Yoyote', zh:'任何', hi:'कोई भी', id:'Apa saja', bn:'যেকোনো', ur:'کوئی بھی', ja:'すべて', ko:'전체' },
  applyFilters: { en:'Apply filters', fr:'Appliquer les filtres', pt:'Aplicar filtros', ar:'تطبيق الفلاتر', sw:'Tumia vichujio', zh:'应用筛选', hi:'फ़िल्टर लागू करें', id:'Terapkan filter', bn:'ফিল্টার প্রয়োগ করুন', ur:'فلٹر لگائیں', ja:'フィルターを適用', ko:'필터 적용' },
  openNowFilter: { en:'Open now', fr:'Ouvert maintenant', pt:'Aberto agora', ar:'مفتوح الآن', sw:'Wazi sasa', zh:'现在营业', hi:'अभी खुला', id:'Buka sekarang', bn:'এখন খোলা', ur:'ابھی کھلا', ja:'営業中', ko:'지금 영업 중' },
  clearAll: { en:'Clear all', fr:'Tout effacer', pt:'Limpar tudo', ar:'مسح الكل', sw:'Futa yote', zh:'清除全部', hi:'सब साफ़ करें', id:'Hapus semua', bn:'সব মুছুন', ur:'سب صاف کریں', ja:'全てクリア', ko:'전체 지우기' },
  all: { en:'All', fr:'Tous', pt:'Todos', ar:'الكل', sw:'Zote', zh:'全部', hi:'सभी', id:'Semua', bn:'সব', ur:'سب', ja:'すべて', ko:'전체' },

  // ── Listing detail (extra) ───────────────────────────────────────────────────
  listingNotFound: { en:'Listing not found', fr:'Annonce introuvable', pt:'Anúncio não encontrado', ar:'الإعلان غير موجود', sw:'Tangazo halipatikani', zh:'商品未找到', hi:'लिस्टिंग नहीं मिली', id:'Listing tidak ditemukan', bn:'তালিকা পাওয়া যায়নি', ur:'فہرست نہیں ملی', ja:'リストが見つかりません', ko:'목록을 찾을 수 없습니다' },
  listingNotFoundDesc: { en:'It may have been removed or the link is incorrect.', fr:'Il a peut-être été supprimé ou le lien est incorrect.', pt:'Pode ter sido removido ou o link está incorreto.', ar:'ربما تم حذفه أو الرابط غير صحيح.', sw:'Inawezekana iliondolewa au kiungo si sahihi.', zh:'可能已被删除或链接不正确。', hi:'इसे हटाया जा सकता है या लिंक गलत है।', id:'Mungkin telah dihapus atau link tidak tepat.', bn:'এটি সরানো হয়েছে বা লিঙ্কটি ভুল।', ur:'شاید اسے ہٹا دیا گیا ہو یا لنک غلط ہو۔', ja:'削除されたかリンクが正しくない可能性があります。', ko:'삭제되었거나 링크가 잘못되었을 수 있습니다.' },
  browseListings: { en:'Browse listings', fr:'Parcourir les annonces', pt:'Navegar pelos anúncios', ar:'تصفح الإعلانات', sw:'Vinjari matangazo', zh:'浏览列表', hi:'लिस्टिंग ब्राउज़ करें', id:'Jelajahi listing', bn:'তালিকা ব্রাউজ করুন', ur:'فہرستیں دیکھیں', ja:'リストを見る', ko:'목록 탐색' },
  specifications: { en:'Specifications', fr:'Spécifications', pt:'Especificações', ar:'المواصفات', sw:'Maelezo ya kiufundi', zh:'规格', hi:'विशेषताएँ', id:'Spesifikasi', bn:'বৈশিষ্ট্য', ur:'وضاحتیں', ja:'仕様', ko:'사양' },
  messageSeller: { en:'Message Seller', fr:'Contacter le vendeur', pt:'Mensagem ao vendedor', ar:'راسل البائع', sw:'Tuma ujumbe kwa muuzaji', zh:'联系卖家', hi:'विक्रेता को संदेश करें', id:'Pesan penjual', bn:'বিক্রেতাকে বার্তা দিন', ur:'بائع کو پیغام بھیجیں', ja:'出品者へメッセージ', ko:'판매자에게 메시지' },
  similarListings: { en:'Similar Listings', fr:'Annonces similaires', pt:'Anúncios semelhantes', ar:'إعلانات مشابهة', sw:'Matangazo yanayofanana', zh:'相似列表', hi:'समान लिस्टिंग', id:'Listing serupa', bn:'অনুরূপ তালিকা', ur:'ملتی جلتی فہرستیں', ja:'類似リスト', ko:'유사 목록' },
  viewsLabel: { en:'views', fr:'vues', pt:'visualizações', ar:'مشاهدة', sw:'maoni', zh:'次浏览', hi:'व्यू', id:'tayangan', bn:'ভিউ', ur:'مناظر', ja:'回視聴', ko:'조회' },
  savesLabel: { en:'saves', fr:'sauvegardes', pt:'salvamentos', ar:'حفظ', sw:'zilizohifadhiwa', zh:'次收藏', hi:'सेव', id:'simpanan', bn:'সেভ', ur:'محفوظ', ja:'件保存', ko:'저장' },
  messagesLabel: { en:'messages', fr:'messages', pt:'mensagens', ar:'رسائل', sw:'ujumbe', zh:'条消息', hi:'संदेश', id:'pesan', bn:'বার্তা', ur:'پیغامات', ja:'件メッセージ', ko:'개 메시지' },
  copied: { en:'Copied!', fr:'Copié!', pt:'Copiado!', ar:'تم النسخ!', sw:'Imenakiliwa!', zh:'已复制！', hi:'कॉपी हो गया!', id:'Disalin!', bn:'কপি হয়েছে!', ur:'کاپی ہو گیا!', ja:'コピーしました！', ko:'복사됨!' },
  copyLink: { en:'Copy link', fr:'Copier le lien', pt:'Copiar link', ar:'نسخ الرابط', sw:'Nakili kiungo', zh:'复制链接', hi:'लिंक कॉपी करें', id:'Salin link', bn:'লিঙ্ক কপি করুন', ur:'لنک کاپی کریں', ja:'リンクをコピー', ko:'링크 복사' },
  seller: { en:'Seller', fr:'Vendeur', pt:'Vendedor', ar:'البائع', sw:'Muuzaji', zh:'卖家', hi:'विक्रेता', id:'Penjual', bn:'বিক্রেতা', ur:'بائع', ja:'出品者', ko:'판매자' },
  languages: { en:'Languages', fr:'Langues', pt:'Idiomas', ar:'اللغات', sw:'Lugha', zh:'语言', hi:'भाषाएँ', id:'Bahasa', bn:'ভাষাসমূহ', ur:'زبانیں', ja:'言語', ko:'언어' },
  freeToStart: { en:'Free to Start', fr:'Gratuit pour commencer', pt:'Gratuito para começar', ar:'مجاني للبدء', sw:'Bure Kuanza', zh:'免费开始', hi:'शुरू करना मुफ्त', id:'Gratis Mulai', bn:'শুরু করতে বিনামূল্যে', ur:'شروع کرنے کے لیے مفت', ja:'無料スタート', ko:'무료로 시작' },
  posted: { en:'Posted', fr:'Publié', pt:'Publicado', ar:'نُشر', sw:'Ilichapishwa', zh:'发布于', hi:'पोस्ट किया', id:'Diposting', bn:'পোস্ট করা হয়েছে', ur:'پوسٹ کیا', ja:'投稿', ko:'게시됨' },

  // ── Feature bullet points ────────────────────────────────────────────────────
  featureModeration: { en:'Content moderation', fr:'Modération du contenu', pt:'Moderação de conteúdo', ar:'إشراف المحتوى', sw:'Udhibiti wa maudhui', zh:'内容审核', hi:'सामग्री मॉडरेशन', id:'Moderasi konten', bn:'কন্টেন্ট মডারেশন', ur:'مواد کی نگرانی', ja:'コンテンツモデレーション', ko:'콘텐츠 관리' },
  featureVerified: { en:'Verified seller badges', fr:'Badges vendeurs vérifiés', pt:'Emblemas de vendedor verificado', ar:'شارات البائع الموثق', sw:'Vibali vya muuzaji aliyethibitishwa', zh:'认证卖家徽章', hi:'सत्यापित विक्रेता बैज', id:'Lencana penjual terverifikasi', bn:'যাচাইকৃত বিক্রেতার ব্যাজ', ur:'تصدیق شدہ بائع بیجز', ja:'認証済み出品者バッジ', ko:'인증된 판매자 배지' },
  featureMapDirections: { en:'Live map directions', fr:'Directions en direct sur la carte', pt:'Direções ao vivo no mapa', ar:'اتجاهات الخريطة المباشرة', sw:'Maelekezo ya ramani ya moja kwa moja', zh:'实时地图导航', hi:'लाइव मैप दिशाएँ', id:'Petunjuk peta langsung', bn:'লাইভ ম্যাপ দিকনির্দেশনা', ur:'لائیو میپ ہدایات', ja:'リアルタイム地図案内', ko:'실시간 지도 안내' },
  featureOpenNow: { en:'Open Now filter', fr:'Filtre Ouvert maintenant', pt:'Filtro Aberto agora', ar:'فلتر مفتوح الآن', sw:'Kichujio cha Wazi Sasa', zh:'"营业中"筛选', hi:'"अभी खुला" फ़िल्टर', id:'Filter Buka Sekarang', bn:'"এখন খোলা" ফিল্টার', ur:'"ابھی کھلا" فلٹر', ja:'"今営業中"フィルター', ko:'"지금 영업 중" 필터' },
  featureMessaging: { en:'Real-time messaging', fr:'Messagerie en temps réel', pt:'Mensagens em tempo real', ar:'المراسلة الفورية', sw:'Ujumbe wa wakati halisi', zh:'实时消息', hi:'रियल-टाइम मैसेजिंग', id:'Pesan real-time', bn:'রিয়েল-টাইম মেসেজিং', ur:'ریئل ٹائم میسجنگ', ja:'リアルタイムメッセージ', ko:'실시간 메시지' },
  noResultsFor: { en:'No results for', fr:'Aucun résultat pour', pt:'Nenhum resultado para', ar:'لا نتائج لـ', sw:'Hakuna matokeo ya', zh:'无相关结果：', hi:'के लिए कोई परिणाम नहीं', id:'Tidak ada hasil untuk', bn:'এর জন্য কোনো ফলাফল নেই', ur:'کے لیے کوئی نتیجہ نہیں', ja:'の検索結果なし：', ko:'의 결과 없음:' },

  // ── User drawer ───────────────────────────────────────────────────────────────
  profile: { en:'Profile', fr:'Profil', pt:'Perfil', ar:'الملف الشخصي', sw:'Wasifu', zh:'个人资料', hi:'प्रोफ़ाइल', id:'Profil', bn:'প্রোফাইল', ur:'پروفائل', ja:'プロフィール', ko:'프로필' },
  menuNote: { en:'For more features, download the Syph app', fr:'Pour plus de fonctionnalités, téléchargez l\'app Syph', pt:'Para mais recursos, baixe o app Syph', ar:'للمزيد من الميزات، حمّل تطبيق Syph', sw:'Kwa vipengele zaidi, pakua app ya Syph', zh:'更多功能请下载Syph应用', hi:'और सुविधाओं के लिए Syph ऐप डाउनलोड करें', id:'Untuk fitur lebih, unduh app Syph', bn:'আরো বৈশিষ্ট্যের জন্য Syph অ্যাপ ডাউনলোড করুন', ur:'مزید فیچرز کے لیے Syph ایپ ڈاؤن لوڈ کریں', ja:'さらなる機能はSyphアプリをダウンロード', ko:'더 많은 기능을 위해 Syph 앱을 다운로드하세요' },

  // ── Seller advantages section ─────────────────────────────────────────────────
  forSellers: { en:'For Sellers & Service Providers', fr:'Pour les vendeurs et prestataires', pt:'Para vendedores e prestadores', ar:'للبائعين ومزودي الخدمات', sw:'Kwa Wauzaji na Watoa Huduma', zh:'面向卖家和服务商', hi:'विक्रेताओं और सेवा प्रदाताओं के लिए', id:'Untuk Penjual & Penyedia Jasa', bn:'বিক্রেতা ও সেবা প্রদানকারীদের জন্য', ur:'بائعوں اور سروس فراہم کنندگان کے لیے', ja:'出品者・サービス提供者向け', ko:'판매자 및 서비스 제공자를 위해' },
  growGloballyTitle: { en:'Grow Your Business Globally', fr:'Développez votre activité mondialement', pt:'Cresça globalmente', ar:'طوّر عملك عالميًا', sw:'Kukuza Biashara Yako Kimataifa', zh:'全球发展您的业务', hi:'अपना व्यवसाय वैश्विक रूप से बढ़ाएं', id:'Kembangkan Bisnis Anda Global', bn:'বিশ্বব্যাপী আপনার ব্যবসা বাড়ান', ur:'اپنا کاروبار عالمی سطح پر بڑھائیں', ja:'ビジネスをグローバルに拡大', ko:'비즈니스를 글로벌하게 성장시키세요' },
  growGloballySubtitle: { en:'Why thousands of sellers trust Syph Global to reach customers worldwide', fr:'Pourquoi des milliers de vendeurs font confiance à Syph Global', pt:'Por que milhares de vendedores confiam no Syph Global', ar:'لماذا يثق آلاف البائعين في Syph Global', sw:'Kwa nini maelfu ya wauzaji wanaamini Syph Global', zh:'数千卖家选择Syph Global的原因', hi:'हजारों विक्रेता Syph Global पर भरोसा क्यों करते हैं', id:'Mengapa ribuan penjual mempercayai Syph Global', bn:'হাজার হাজার বিক্রেতা কেন Syph Global বিশ্বাস করেন', ur:'ہزاروں بائع Syph Global پر کیوں بھروسہ کرتے ہیں', ja:'数千の出品者がSyph Globalを選ぶ理由', ko:'수천 명의 판매자가 Syph Global을 선택하는 이유' },
  adv1Title: { en:'International Audience', fr:'Audience internationale', pt:'Público internacional', ar:'جمهور دولي', sw:'Hadhira ya Kimataifa', zh:'国际受众', hi:'अंतर्राष्ट्रीय दर्शक', id:'Audiens Internasional', bn:'আন্তর্জাতিক দর্শক', ur:'بین الاقوامی سامعین', ja:'国際的なオーディエンス', ko:'국제 고객' },
  adv1Desc: { en:'Reach buyers in 50+ countries — no borders, no agents, no overhead', fr:'Atteignez des acheteurs dans 50+ pays sans intermédiaires', pt:'Alcance compradores em 50+ países sem intermediários', ar:'وصل إلى المشترين في أكثر من 50 دولة بدون وسطاء', sw:'Fikia wanunuzi katika nchi 50+ bila mawakala', zh:'覆盖50+国家的买家——无需中间商', hi:'50+ देशों में खरीदारों तक पहुँचें — कोई बिचौलिया नहीं', id:'Jangkau pembeli di 50+ negara tanpa perantara', bn:'৫০+ দেশে ক্রেতাদের কাছে পৌঁছান — কোনো মধ্যস্থতাকারী নেই', ur:'50+ ممالک میں خریداروں تک پہنچیں — کوئی دلال نہیں', ja:'50以上の国の購入者にリーチ — 仲介業者なし', ko:'50개 이상의 국가 구매자에게 직접 도달' },
  adv2Title: { en:'Instant Visibility', fr:'Visibilité instantanée', pt:'Visibilidade instantânea', ar:'رؤية فورية', sw:'Mwonekano wa Haraka', zh:'即时曝光', hi:'तुरंत दृश्यता', id:'Visibilitas Instan', bn:'তাৎক্ষণিক দৃশ্যমানতা', ur:'فوری مرئیت', ja:'即時の露出', ko:'즉각적인 노출' },
  adv2Desc: { en:'Listings go live in minutes — admin-reviewed, trusted, and discoverable', fr:'Annonces en direct en quelques minutes, vérifiées par admin', pt:'Anúncios no ar em minutos — revisados e confiáveis', ar:'تنشر إعلاناتك في دقائق — تُراجع وتُثق بها', sw:'Matangazo yanaonekana kwa dakika — yapitiwa na admin', zh:'几分钟内上线——经管理员审核，值得信赖', hi:'लिस्टिंग मिनटों में लाइव — एडमिन-समीक्षित', id:'Listing aktif dalam menit — ditinjau admin', bn:'মিনিটের মধ্যে লাইভ তালিকা — অ্যাডমিন-পর্যালোচিত', ur:'فہرستیں منٹوں میں لائیو — ایڈمن کی جانچ شدہ', ja:'数分で公開 — 管理者レビュー済み', ko:'몇 분 안에 등록 — 관리자 검토 완료' },
  adv3Title: { en:'Customers Come to You', fr:'Les clients viennent à vous', pt:'Clientes chegam até você', ar:'العملاء يأتون إليك', sw:'Wateja Wanakuja Kwako', zh:'客户主动找上门', hi:'ग्राहक आपके पास आएंगे', id:'Pelanggan Datang ke Anda', bn:'গ্রাহকরা আপনার কাছে আসে', ur:'گاہک آپ کے پاس آتے ہیں', ja:'顧客があなたのもとへ', ko:'고객이 직접 찾아옵니다' },
  adv3Desc: { en:'Buyers get live map directions straight to your location — more foot traffic, zero effort', fr:'Les acheteurs obtiennent des directions en direct vers votre emplacement', pt:'Compradores recebem direções ao vivo para sua localização', ar:'يحصل المشترون على اتجاهات مباشرة إلى موقعك', sw:'Wanunuzi wanapata maelekezo ya ramani moja kwa moja kwako', zh:'买家可直接获得导航到您位置的路线', hi:'खरीदार सीधे आपके स्थान पर लाइव मैप दिशाएँ पाते हैं', id:'Pembeli mendapat petunjuk peta langsung ke lokasi Anda', bn:'ক্রেতারা সরাসরি আপনার অবস্থানে লাইভ ম্যাপ নির্দেশনা পান', ur:'خریدار آپ کی جگہ تک لائیو نقشہ ہدایات حاصل کرتے ہیں', ja:'購入者があなたの場所への経路案内を受け取れます', ko:'구매자가 귀하의 위치까지 실시간 지도 안내를 받습니다' },
  startSellingFree: { en:'Start Selling Free', fr:'Commencer à vendre gratuitement', pt:'Comece a vender grátis', ar:'ابدأ البيع مجانًا', sw:'Anza Kuuza Bure', zh:'免费开始销售', hi:'मुफ्त में बेचना शुरू करें', id:'Mulai Jual Gratis', bn:'বিনামূল্যে বিক্রি শুরু করুন', ur:'مفت بیچنا شروع کریں', ja:'無料で出品開始', ko:'무료로 판매 시작' },

  // ── Consumer benefits section ──────────────────────────────────────────────────
  forBuyers: { en:'For Buyers', fr:'Pour les acheteurs', pt:'Para compradores', ar:'للمشترين', sw:'Kwa Wanunuzi', zh:'对于买家', hi:'खरीदारों के लिए', id:'Untuk Pembeli', bn:'ক্রেতাদের জন্য', ur:'خریداروں کے لیے', ja:'購入者向け', ko:'구매자를 위해' },
  shopSmarterTitle: { en:'Shop Smarter, Anywhere', fr:'Achetez mieux, partout', pt:'Compre com inteligência, em qualquer lugar', ar:'تسوّق بذكاء في أي مكان', sw:'Nunua kwa Akili, Popote', zh:'聪明购物，随时随地', hi:'स्मार्ट शॉपिंग, कहीं भी', id:'Belanja Cerdas, Di Mana Saja', bn:'স্মার্ট শপিং, যেকোনো জায়গায়', ur:'سمارٹ شاپنگ، کہیں بھی', ja:'スマートに買い物、どこでも', ko:'어디서나 스마트하게 쇼핑하세요' },
  shopSmarterSubtitle: { en:'Why buyers worldwide trust Syph Global for fair, direct deals', fr:'Pourquoi les acheteurs du monde entier font confiance à Syph Global', pt:'Por que compradores do mundo todo confiam no Syph Global', ar:'لماذا يثق المشترون حول العالم في Syph Global', sw:'Kwa nini wanunuzi duniani kote wanaamini Syph Global', zh:'为什么全球买家信任Syph Global', hi:'दुनिया भर के खरीदार Syph Global पर क्यों भरोसा करते हैं', id:'Mengapa pembeli di seluruh dunia mempercayai Syph Global', bn:'কেন সারা বিশ্বের ক্রেতারা Syph Global বিশ্বাস করেন', ur:'دنیا بھر کے خریدار Syph Global پر کیوں بھروسہ کرتے ہیں', ja:'世界中の購入者がSyph Globalを信頼する理由', ko:'전 세계 구매자들이 Syph Global을 신뢰하는 이유' },
  ben1Title: { en:'Live Map Directions', fr:'Directions en direct sur la carte', pt:'Direções ao vivo no mapa', ar:'اتجاهات الخريطة المباشرة', sw:'Maelekezo ya Ramani ya Moja kwa Moja', zh:'实时地图导航', hi:'लाइव मैप दिशाएँ', id:'Petunjuk Peta Langsung', bn:'লাইভ ম্যাপ নির্দেশনা', ur:'لائیو میپ ہدایات', ja:'リアルタイム地図案内', ko:'실시간 지도 안내' },
  ben1Desc: { en:'Navigate directly to any seller or service provider — turn-by-turn, no guessing', fr:'Naviguez directement vers n\'importe quel vendeur — itinéraire étape par étape', pt:'Navegue diretamente para qualquer vendedor — rota passo a passo', ar:'انتقل مباشرة إلى أي بائع — خطوة بخطوة', sw:'Nenda moja kwa moja kwa muuzaji yeyote — hatua kwa hatua', zh:'直接导航到任何卖家——逐步路线指引', hi:'किसी भी विक्रेता तक सीधे नेविगेट करें — चरण-दर-चरण', id:'Navigasi langsung ke penjual mana pun — langkah demi langkah', bn:'যেকোনো বিক্রেতার কাছে সরাসরি নেভিগেট করুন — পদক্ষেপে পদক্ষেপে', ur:'کسی بھی بائع تک براہ راست نیوی گیٹ کریں — قدم بقدم', ja:'どの出品者へも直接ナビゲート — ターンバイターン案内', ko:'어느 판매자에게도 직접 내비게이션 — 턴바이턴 안내' },
  ben2Title: { en:'Shop from Any Country', fr:'Achetez depuis n\'importe quel pays', pt:'Compre de qualquer país', ar:'تسوّق من أي دولة', sw:'Nunua kutoka Nchi Yoyote', zh:'从任何国家购物', hi:'किसी भी देश से खरीदारी', id:'Belanja dari Negara Mana Pun', bn:'যেকোনো দেশ থেকে কেনাকাটা', ur:'کسی بھی ملک سے خریداری', ja:'どの国からでも購入', ko:'어느 나라에서든 쇼핑' },
  ben2Desc: { en:'Access listings from 50+ countries directly — no middlemen, no import agents needed', fr:'Accédez aux annonces de 50+ pays directement — sans intermédiaires', pt:'Acesse anúncios de 50+ países diretamente — sem intermediários', ar:'وصل إلى إعلانات من أكثر من 50 دولة مباشرة — بدون وسطاء', sw:'Fikia matangazo kutoka nchi 50+ moja kwa moja — bila mawakala', zh:'直接访问50+国家的商品——无需中间商', hi:'50+ देशों की लिस्टिंग सीधे एक्सेस करें — कोई बिचौलिया नहीं', id:'Akses listing dari 50+ negara langsung — tanpa perantara', bn:'৫০+ দেশের তালিকায় সরাসরি প্রবেশ — কোনো মধ্যস্থতাকারী নেই', ur:'50+ ممالک سے فہرستیں براہ راست — کوئی دلال نہیں', ja:'50以上の国のリストに直接アクセス — 仲介業者なし', ko:'50개 이상 국가의 상품에 직접 접근 — 중간상 없음' },
  ben3Title: { en:'Fair, Direct Prices', fr:'Prix justes et directs', pt:'Preços justos e diretos', ar:'أسعار عادلة ومباشرة', sw:'Bei za Haki na za Moja kwa Moja', zh:'公平直接的价格', hi:'उचित, सीधी कीमतें', id:'Harga Langsung & Adil', bn:'ন্যায্য ও সরাসরি মূল্য', ur:'منصفانہ، براہ راست قیمتیں', ja:'公正・直接価格', ko:'공정하고 직접적인 가격' },
  ben3Desc: { en:'Buy straight from sellers — no markups, no middlemen, always transparent pricing', fr:'Achetez directement aux vendeurs — sans majoration ni intermédiaires', pt:'Compre diretamente dos vendedores — sem taxas extras ou intermediários', ar:'اشترِ مباشرة من البائعين — بدون زيادات أو وسطاء', sw:'Nunua moja kwa moja kwa wauzaji — bila ziada au mawakala', zh:'直接从卖家购买——无加价，无中间商', hi:'विक्रेताओं से सीधे खरीदें — कोई मार्कअप नहीं, कोई बिचौलिया नहीं', id:'Beli langsung dari penjual — tanpa markup atau perantara', bn:'বিক্রেতাদের কাছ থেকে সরাসরি কিনুন — কোনো মার্কআপ নেই', ur:'بائعوں سے براہ راست خریدیں — کوئی مارک اپ نہیں، کوئی دلال نہیں', ja:'出品者から直接購入 — 追加料金なし、仲介業者なし', ko:'판매자에게 직접 구매 — 마크업 없음, 중간상 없음' },
  discoverListings: { en:'Discover Listings', fr:'Découvrir les annonces', pt:'Descobrir anúncios', ar:'اكتشف الإعلانات', sw:'Gundua Matangazo', zh:'探索列表', hi:'लिस्टिंग देखें', id:'Temukan Listing', bn:'তালিকা আবিষ্কার করুন', ur:'فہرستیں دریافت کریں', ja:'リストを見る', ko:'목록 탐색' },

  // ── Home social-proof stats ───────────────────────────────────────────────────
  categoriesStatDesc: { en:'From real estate to happenings', fr:"De l'immobilier aux événements", pt:'De imóveis a eventos', ar:'من العقارات إلى الأحداث', sw:'Kutoka mali hadi matukio', zh:'从房产到活动', hi:'रियल एस्टेट से इवेंट तक', id:'Dari properti hingga acara', bn:'রিয়েল এস্টেট থেকে ইভেন্ট', ur:'رئیل اسٹیٹ سے واقعات تک', ja:'不動産からイベントまで', ko:'부동산부터 이벤트까지' },
  countriesStatDesc: { en:'Sellers and buyers globally', fr:'Vendeurs et acheteurs dans le monde', pt:'Vendedores e compradores globalmente', ar:'بائعون ومشترون عالميًا', sw:'Wauzaji na wanunuzi duniani', zh:'全球买卖双方', hi:'वैश्विक विक्रेता और खरीदार', id:'Penjual dan pembeli global', bn:'বিশ্বজুড়ে ক্রেতা ও বিক্রেতা', ur:'عالمی سطح پر خریداران اور بائعین', ja:'世界中の売買', ko:'전 세계 구매자와 판매자' },
  languagesStatDesc: { en:'Available in the mobile app', fr:"Disponible dans l'app mobile", pt:'Disponível no app mobile', ar:'متاح في التطبيق', sw:'Inapatikana kwenye app', zh:'移动App可用', hi:'मोबाइल ऐप में उपलब्ध', id:'Tersedia di app mobile', bn:'মোবাইল অ্যাপে পাওয়া যায়', ur:'موبائل ایپ میں دستیاب', ja:'モバイルアプリで利用可能', ko:'모바일 앱에서 사용 가능' },
  freeTrialDesc: { en:'4-month trial, no card needed', fr:'Essai de 4 mois, sans carte', pt:'4 meses de teste, sem cartão', ar:'تجربة 4 أشهر بدون بطاقة', sw:'Jaribio la miezi 4, bila kadi', zh:'4个月试用，无需信用卡', hi:'4 महीने का ट्रायल, कोई कार्ड नहीं', id:'Uji coba 4 bulan, tanpa kartu', bn:'4 মাসের ট্রায়াল, কোনো কার্ড নেই', ur:'4 ماہ کا ٹرائل، کوئی کارڈ نہیں', ja:'4ヶ月トライアル、カード不要', ko:'4개월 무료 체험, 카드 불필요' },

  // ── Auth extra ────────────────────────────────────────────────────────────────
  forgotPasswordDesc:  { en:'Enter your email and we\'ll send a reset link.', fr:'Entrez votre email pour recevoir un lien de réinitialisation.', pt:'Insira seu email para receber um link de redefinição.', ar:'أدخل بريدك لإرسال رابط إعادة التعيين.', sw:'Weka barua pepe yako tupeleke kiungo cha kurekebisha.', zh:'输入邮箱，我们将发送重置链接。', hi:'ईमेल दर्ज करें और हम एक रीसेट लिंक भेजेंगे।', id:'Masukkan email Anda dan kami akan mengirim tautan reset.', bn:'আপনার ইমেইল দিন এবং আমরা একটি রিসেট লিংক পাঠাব।', ur:'اپنی ای میل درج کریں، ہم ری سیٹ لنک بھیجیں گے۔', ja:'メールアドレスを入力するとリセットリンクを送ります。', ko:'이메일을 입력하시면 재설정 링크를 보내드립니다.' },
  resetLinkSent:       { en:'Reset link sent! Check your inbox.', fr:'Lien envoyé ! Vérifiez votre boîte.', pt:'Link enviado! Verifique seu email.', ar:'تم إرسال الرابط! تحقق من بريدك.', sw:'Kiungo kimetumwa! Angalia kikasha chako.', zh:'重置链接已发送！请检查您的收件箱。', hi:'रीसेट लिंक भेजा गया! अपना इनबॉक्स जांचें।', id:'Link reset terkirim! Cek kotak masuk Anda.', bn:'রিসেট লিংক পাঠানো হয়েছে! আপনার ইনবক্স চেক করুন।', ur:'ری سیٹ لنک بھیج دیا گیا! اپنا ان باکس چیک کریں۔', ja:'リセットリンクを送りました。受信トレイをご確認ください。', ko:'재설정 링크를 보냈습니다! 받은 편지함을 확인하세요.' },
  backToSignIn:        { en:'Back to Sign In', fr:'Retour à la connexion', pt:'Voltar para o login', ar:'العودة لتسجيل الدخول', sw:'Rudi kwa Kuingia', zh:'返回登录', hi:'साइन इन पर वापस', id:'Kembali ke Login', bn:'সাইন ইনে ফিরুন', ur:'سائن ان پر واپس', ja:'サインインに戻る', ko:'로그인으로 돌아가기' },
  signInToView:        { en:'Sign in to view this page', fr:'Connectez-vous pour voir cette page', pt:'Entre para ver esta página', ar:'سجّل الدخول لعرض هذه الصفحة', sw:'Ingia ili kuona ukurasa huu', zh:'登录以查看此页面', hi:'इस पृष्ठ को देखने के लिए साइन इन करें', id:'Masuk untuk melihat halaman ini', bn:'এই পেজ দেখতে সাইন ইন করুন', ur:'اس صفحے کو دیکھنے کے لیے سائن ان کریں', ja:'このページを表示するにはサインインしてください', ko:'이 페이지를 보려면 로그인하세요' },
  signingIn:           { en:'Signing in...', fr:'Connexion...', pt:'Entrando...', ar:'جارٍ تسجيل الدخول...', sw:'Inaingia...', zh:'登录中...', hi:'साइन इन हो रहा है...', id:'Masuk...', bn:'সাইন ইন হচ্ছে...', ur:'سائن ان ہو رہا ہے...', ja:'サインイン中...', ko:'로그인 중...' },

  // ── Profile page ──────────────────────────────────────────────────────────────
  myProfile:           { en:'My Profile', fr:'Mon profil', pt:'Meu perfil', ar:'ملفي الشخصي', sw:'Wasifu Wangu', zh:'我的资料', hi:'मेरी प्रोफ़ाइल', id:'Profil Saya', bn:'আমার প্রোফাইল', ur:'میری پروفائل', ja:'マイプロフィール', ko:'내 프로필' },
  editProfile:         { en:'Edit Profile', fr:'Modifier le profil', pt:'Editar perfil', ar:'تعديل الملف الشخصي', sw:'Hariri Wasifu', zh:'编辑资料', hi:'प्रोफ़ाइल संपादित करें', id:'Edit Profil', bn:'প্রোফাইল সম্পাদনা', ur:'پروفائل ترمیم', ja:'プロフィールを編集', ko:'프로필 편집' },
  displayName:         { en:'Display Name', fr:'Nom affiché', pt:'Nome de exibição', ar:'الاسم المعروض', sw:'Jina la Kuonyesha', zh:'显示名称', hi:'प्रदर्शन नाम', id:'Nama Tampilan', bn:'প্রদর্শন নাম', ur:'ڈسپلے نام', ja:'表示名', ko:'표시 이름' },
  changePassword:      { en:'Change Password', fr:'Changer le mot de passe', pt:'Alterar senha', ar:'تغيير كلمة المرور', sw:'Badilisha Nenosiri', zh:'修改密码', hi:'पासवर्ड बदलें', id:'Ubah Kata Sandi', bn:'পাসওয়ার্ড পরিবর্তন', ur:'پاسورڈ تبدیل کریں', ja:'パスワード変更', ko:'비밀번호 변경' },
  currentPassword:     { en:'Current Password', fr:'Mot de passe actuel', pt:'Senha atual', ar:'كلمة المرور الحالية', sw:'Nenosiri la Sasa', zh:'当前密码', hi:'वर्तमान पासवर्ड', id:'Kata Sandi Saat Ini', bn:'বর্তমান পাসওয়ার্ড', ur:'موجودہ پاسورڈ', ja:'現在のパスワード', ko:'현재 비밀번호' },
  newPassword:         { en:'New Password', fr:'Nouveau mot de passe', pt:'Nova senha', ar:'كلمة المرور الجديدة', sw:'Nenosiri Jipya', zh:'新密码', hi:'नया पासवर्ड', id:'Kata Sandi Baru', bn:'নতুন পাসওয়ার্ড', ur:'نیا پاسورڈ', ja:'新しいパスワード', ko:'새 비밀번호' },
  profileUpdated:      { en:'Profile updated!', fr:'Profil mis à jour !', pt:'Perfil atualizado!', ar:'تم تحديث الملف الشخصي!', sw:'Wasifu umesasishwa!', zh:'资料已更新！', hi:'प्रोफ़ाइल अपडेट हो गई!', id:'Profil diperbarui!', bn:'প্রোফাইল আপডেট হয়েছে!', ur:'پروفائل اپ ڈیٹ ہو گئی!', ja:'プロフィールを更新しました！', ko:'프로필이 업데이트되었습니다!' },
  passwordChanged:     { en:'Password changed!', fr:'Mot de passe modifié !', pt:'Senha alterada!', ar:'تم تغيير كلمة المرور!', sw:'Nenosiri limebadilishwa!', zh:'密码已更改！', hi:'पासवर्ड बदल गया!', id:'Kata sandi diubah!', bn:'পাসওয়ার্ড পরিবর্তন হয়েছে!', ur:'پاسورڈ تبدیل ہو گیا!', ja:'パスワードを変更しました！', ko:'비밀번호가 변경되었습니다!' },
  uploadPhoto:         { en:'Upload Photo', fr:'Télécharger une photo', pt:'Enviar foto', ar:'رفع صورة', sw:'Pakia Picha', zh:'上传照片', hi:'फ़ोटो अपलोड करें', id:'Unggah Foto', bn:'ছবি আপলোড করুন', ur:'تصویر اپ لوڈ کریں', ja:'写真をアップロード', ko:'사진 업로드' },
  saveChanges:         { en:'Save Changes', fr:'Enregistrer les modifications', pt:'Salvar alterações', ar:'حفظ التغييرات', sw:'Hifadhi Mabadiliko', zh:'保存更改', hi:'परिवर्तन सहेजें', id:'Simpan Perubahan', bn:'পরিবর্তন সংরক্ষণ করুন', ur:'تبدیلیاں محفوظ کریں', ja:'変更を保存', ko:'변경 저장' },
  myListings:          { en:'My Listings', fr:'Mes annonces', pt:'Meus anúncios', ar:'إعلاناتي', sw:'Matangazo Yangu', zh:'我的商品', hi:'मेरी लिस्टिंग', id:'Listing Saya', bn:'আমার তালিকা', ur:'میری فہرستیں', ja:'自分のリスト', ko:'내 목록' },
  sellerProfile:       { en:'Seller Profile', fr:'Profil vendeur', pt:'Perfil do vendedor', ar:'ملف البائع', sw:'Wasifu wa Muuzaji', zh:'卖家资料', hi:'विक्रेता प्रोफ़ाइल', id:'Profil Penjual', bn:'বিক্রেতা প্রোফাইল', ur:'فروخت کنندہ پروفائل', ja:'出品者プロフィール', ko:'판매자 프로필' },

  // ── Messages page ──────────────────────────────────────────────────────────────
  inbox:               { en:'Inbox', fr:'Boîte de réception', pt:'Caixa de entrada', ar:'صندوق الوارد', sw:'Kisanduku cha Barua', zh:'收件箱', hi:'इनबॉक्स', id:'Kotak Masuk', bn:'ইনবক্স', ur:'ان باکس', ja:'受信トレイ', ko:'받은 편지함' },
  noMessages:          { en:'No messages yet', fr:'Pas encore de messages', pt:'Nenhuma mensagem ainda', ar:'لا توجد رسائل بعد', sw:'Bado hakuna ujumbe', zh:'暂无消息', hi:'अभी कोई संदेश नहीं', id:'Belum ada pesan', bn:'এখনো কোনো বার্তা নেই', ur:'ابھی کوئی پیغام نہیں', ja:'まだメッセージはありません', ko:'아직 메시지가 없습니다' },
  noMessagesDesc:      { en:'Start a conversation by messaging a seller from any listing.', fr:'Commencez une conversation depuis une annonce.', pt:'Inicie uma conversa enviando mensagem a um vendedor.', ar:'ابدأ محادثة بمراسلة بائع من أي إعلان.', sw:'Anza mazungumzo kwa kutuma ujumbe kwa muuzaji.', zh:'从任何商品页面发送消息给卖家，开始对话。', hi:'किसी भी लिस्टिंग से विक्रेता को संदेश भेजकर बातचीत शुरू करें।', id:'Mulai percakapan dengan mengirim pesan ke penjual dari listing mana pun.', bn:'যেকোনো তালিকা থেকে বিক্রেতাকে বার্তা পাঠিয়ে কথোপকথন শুরু করুন।', ur:'کسی بھی فہرست سے بائع کو پیغام بھیج کر بات چیت شروع کریں۔', ja:'どのリストからでも出品者にメッセージを送って会話を始めましょう。', ko:'어떤 목록에서든 판매자에게 메시지를 보내 대화를 시작하세요.' },
  typeMessage:         { en:'Type a message…', fr:'Tapez un message…', pt:'Digite uma mensagem…', ar:'اكتب رسالة…', sw:'Andika ujumbe…', zh:'输入消息…', hi:'एक संदेश टाइप करें…', id:'Ketik pesan…', bn:'একটি বার্তা টাইপ করুন…', ur:'پیغام لکھیں…', ja:'メッセージを入力…', ko:'메시지 입력…' },
  you:                 { en:'You', fr:'Vous', pt:'Você', ar:'أنت', sw:'Wewe', zh:'你', hi:'आप', id:'Anda', bn:'আপনি', ur:'آپ', ja:'あなた', ko:'나' },
  unread:              { en:'unread', fr:'non lu', pt:'não lido', ar:'غير مقروء', sw:'haijasomwa', zh:'未读', hi:'अपठित', id:'belum dibaca', bn:'অপঠিত', ur:'غیر پڑھا', ja:'未読', ko:'읽지 않음' },

  // ── Seller Dashboard ──────────────────────────────────────────────────────────
  dashboard:           { en:'Dashboard', fr:'Tableau de bord', pt:'Painel', ar:'لوحة التحكم', sw:'Dashibodi', zh:'仪表盘', hi:'डैशबोर्ड', id:'Dasbor', bn:'ড্যাশবোর্ড', ur:'ڈیش بورڈ', ja:'ダッシュボード', ko:'대시보드' },
  postListing:         { en:'Post a Listing', fr:'Publier une annonce', pt:'Publicar anúncio', ar:'نشر إعلان', sw:'Weka Tangazo', zh:'发布商品', hi:'लिस्टिंग पोस्ट करें', id:'Pasang Listing', bn:'তালিকা পোস্ট করুন', ur:'فہرست پوسٹ کریں', ja:'リストを投稿', ko:'목록 게시' },
  newListing:          { en:'New Listing', fr:'Nouvelle annonce', pt:'Novo anúncio', ar:'إعلان جديد', sw:'Tangazo Jipya', zh:'新商品', hi:'नई लिस्टिंग', id:'Listing Baru', bn:'নতুন তালিকা', ur:'نئی فہرست', ja:'新しいリスト', ko:'새 목록' },
  editListing:         { en:'Edit Listing', fr:"Modifier l'annonce", pt:'Editar anúncio', ar:'تعديل الإعلان', sw:'Hariri Tangazo', zh:'编辑商品', hi:'लिस्टिंग संपादित करें', id:'Edit Listing', bn:'তালিকা সম্পাদনা', ur:'فہرست ترمیم', ja:'リストを編集', ko:'목록 편집' },
  deleteListing:       { en:'Delete', fr:'Supprimer', pt:'Excluir', ar:'حذف', sw:'Futa', zh:'删除', hi:'हटाएं', id:'Hapus', bn:'মুছুন', ur:'حذف کریں', ja:'削除', ko:'삭제' },
  confirmDelete:       { en:'Delete this listing? This cannot be undone.', fr:'Supprimer cette annonce ? Cela est irréversible.', pt:'Excluir este anúncio? Isso não pode ser desfeito.', ar:'حذف هذا الإعلان؟ لا يمكن التراجع عن هذا.', sw:'Futa tangazo hili? Hii haiwezi kutenduliwa.', zh:'删除此商品？此操作无法撤销。', hi:'इस लिस्टिंग को हटाएं? इसे पूर्ववत नहीं किया जा सकता।', id:'Hapus listing ini? Tidak bisa dibatalkan.', bn:'এই তালিকাটি মুছবেন? এটি পূর্বাবস্থায় ফেরানো যাবে না।', ur:'اس فہرست کو حذف کریں؟ یہ واپس نہیں ہو سکتا۔', ja:'このリストを削除しますか？元に戻せません。', ko:'이 목록을 삭제하시겠습니까? 되돌릴 수 없습니다.' },
  listingDeleted:      { en:'Listing deleted.', fr:'Annonce supprimée.', pt:'Anúncio excluído.', ar:'تم حذف الإعلان.', sw:'Tangazo limefutwa.', zh:'商品已删除。', hi:'लिस्टिंग हटा दी गई।', id:'Listing dihapus.', bn:'তালিকা মুছে গেছে।', ur:'فہرست حذف ہو گئی۔', ja:'リストを削除しました。', ko:'목록이 삭제되었습니다.' },
  listingSubmitted:    { en:'Listing submitted for review!', fr:'Annonce soumise pour examen !', pt:'Anúncio enviado para revisão!', ar:'تم إرسال الإعلان للمراجعة!', sw:'Tangazo limewasilishwa kwa mapitio!', zh:'商品已提交审核！', hi:'लिस्टिंग समीक्षा के लिए सबमिट की गई!', id:'Listing dikirim untuk ditinjau!', bn:'তালিকা পর্যালোচনার জন্য জমা হয়েছে!', ur:'فہرست جائزے کے لیے جمع کر دی گئی!', ja:'リストをレビューに送信しました！', ko:'목록이 검토를 위해 제출되었습니다!' },
  listingUpdated:      { en:'Listing updated!', fr:'Annonce mise à jour !', pt:'Anúncio atualizado!', ar:'تم تحديث الإعلان!', sw:'Tangazo limesasishwa!', zh:'商品已更新！', hi:'लिस्टिंग अपडेट हो गई!', id:'Listing diperbarui!', bn:'তালিকা আপডেট হয়েছে!', ur:'فہرست اپ ڈیٹ ہو گئی!', ja:'リストを更新しました！', ko:'목록이 업데이트되었습니다!' },
  statusPending:       { en:'Pending Review', fr:'En attente de révision', pt:'Aguardando revisão', ar:'قيد المراجعة', sw:'Inasubiri Ukaguzi', zh:'待审核', hi:'समीक्षा लंबित', id:'Menunggu Tinjauan', bn:'পর্যালোচনা বাকি', ur:'جائزے کا انتظار', ja:'審査中', ko:'검토 대기 중' },
  statusApproved:      { en:'Approved', fr:'Approuvé', pt:'Aprovado', ar:'معتمد', sw:'Imeidhinishwa', zh:'已批准', hi:'स्वीकृत', id:'Disetujui', bn:'অনুমোদিত', ur:'منظور شدہ', ja:'承認済み', ko:'승인됨' },
  statusRejected:      { en:'Rejected', fr:'Rejeté', pt:'Rejeitado', ar:'مرفوض', sw:'Imekataliwa', zh:'已拒绝', hi:'अस्वीकृत', id:'Ditolak', bn:'প্রত্যাখ্যাত', ur:'مسترد', ja:'拒否済み', ko:'거절됨' },
  promoteListingBtn:   { en:'Promote', fr:'Promouvoir', pt:'Promover', ar:'ترويج', sw:'Tangaza', zh:'推广', hi:'प्रमोट करें', id:'Promosikan', bn:'প্রচার করুন', ur:'فروغ دیں', ja:'プロモート', ko:'홍보' },
  sellerSetupTitle:    { en:'Set up your seller profile', fr:'Configurez votre profil vendeur', pt:'Configure seu perfil de vendedor', ar:'أعد ملف البائع الخاص بك', sw:'Weka wasifu wa muuzaji wako', zh:'设置您的卖家资料', hi:'अपना विक्रेता प्रोफ़ाइल सेट करें', id:'Siapkan profil penjual Anda', bn:'আপনার বিক্রেতা প্রোফাইল সেট আপ করুন', ur:'اپنی فروخت کنندہ پروفائل ترتیب دیں', ja:'出品者プロフィールを設定する', ko:'판매자 프로필 설정' },
  sellerSetupDesc:     { en:'Complete your business profile to start posting listings.', fr:'Complétez votre profil pour commencer à publier des annonces.', pt:'Complete seu perfil para começar a publicar anúncios.', ar:'أكمل ملفك لبدء نشر الإعلانات.', sw:'Kamilisha wasifu wako ili kuanza kuweka matangazo.', zh:'完善您的商家资料以开始发布商品。', hi:'लिस्टिंग पोस्ट करना शुरू करने के लिए अपनी बिज़नेस प्रोफ़ाइल पूरी करें।', id:'Lengkapi profil bisnis Anda untuk mulai memposting listing.', bn:'তালিকা পোস্ট করা শুরু করতে আপনার ব্যবসা প্রোফাইল সম্পূর্ণ করুন।', ur:'فہرستیں پوسٹ کرنا شروع کرنے کے لیے اپنی کاروباری پروفائل مکمل کریں۔', ja:'リストの投稿を始めるには、ビジネスプロフィールを完成させてください。', ko:'목록 게시를 시작하려면 비즈니스 프로필을 완성하세요.' },
  businessName:        { en:'Business / Seller Name', fr:'Nom de l\'entreprise', pt:'Nome do negócio', ar:'اسم العمل', sw:'Jina la Biashara', zh:'商家名称', hi:'व्यवसाय का नाम', id:'Nama Bisnis', bn:'ব্যবসার নাম', ur:'کاروبار کا نام', ja:'ビジネス名', ko:'비즈니스 이름' },
  businessPhone:       { en:'Business Phone', fr:'Téléphone professionnel', pt:'Telefone comercial', ar:'هاتف العمل', sw:'Simu ya Biashara', zh:'商家电话', hi:'व्यवसाय फ़ोन', id:'Telepon Bisnis', bn:'ব্যবসার ফোন', ur:'کاروباری فون', ja:'ビジネス電話', ko:'비즈니스 전화' },
  operatingCountry:    { en:'Operating Country', fr:'Pays d\'exploitation', pt:'País de operação', ar:'بلد العمل', sw:'Nchi ya Uendeshaji', zh:'运营国家', hi:'संचालन देश', id:'Negara Operasi', bn:'অপারেটিং দেশ', ur:'آپریٹنگ ملک', ja:'運営国', ko:'운영 국가' },
  operatingRegion:     { en:'City / Region', fr:'Ville / Région', pt:'Cidade / Região', ar:'المدينة / المنطقة', sw:'Mji / Mkoa', zh:'城市/地区', hi:'शहर / क्षेत्र', id:'Kota / Wilayah', bn:'শহর / অঞ্চল', ur:'شہر / علاقہ', ja:'都市/地域', ko:'도시/지역' },

  // ── Listing form ──────────────────────────────────────────────────────────────
  listingTitle:        { en:'Title', fr:'Titre', pt:'Título', ar:'العنوان', sw:'Kichwa', zh:'标题', hi:'शीर्षक', id:'Judul', bn:'শিরোনাম', ur:'عنوان', ja:'タイトル', ko:'제목' },
  listingDescription:  { en:'Description', fr:'Description', pt:'Descrição', ar:'الوصف', sw:'Maelezo', zh:'描述', hi:'विवरण', id:'Deskripsi', bn:'বিবরণ', ur:'تفصیل', ja:'説明', ko:'설명' },
  listingPrice:        { en:'Price', fr:'Prix', pt:'Preço', ar:'السعر', sw:'Bei', zh:'价格', hi:'कीमत', id:'Harga', bn:'মূল্য', ur:'قیمت', ja:'価格', ko:'가격' },
  listingCondition:    { en:'Condition', fr:'État', pt:'Condição', ar:'الحالة', sw:'Hali', zh:'状态', hi:'स्थिति', id:'Kondisi', bn:'অবস্থা', ur:'حالت', ja:'状態', ko:'상태' },
  listingImages:       { en:'Photos (up to 6)', fr:'Photos (jusqu\'à 6)', pt:'Fotos (até 6)', ar:'الصور (حتى 6)', sw:'Picha (hadi 6)', zh:'照片（最多6张）', hi:'फ़ोटो (6 तक)', id:'Foto (hingga 6)', bn:'ছবি (সর্বাধিক ৬)', ur:'تصاویر (6 تک)', ja:'写真（最大6枚）', ko:'사진 (최대 6장)' },
  addPhotos:           { en:'Add Photos', fr:'Ajouter des photos', pt:'Adicionar fotos', ar:'إضافة صور', sw:'Ongeza Picha', zh:'添加照片', hi:'फ़ोटो जोड़ें', id:'Tambah Foto', bn:'ছবি যোগ করুন', ur:'تصاویر شامل کریں', ja:'写真を追加', ko:'사진 추가' },
  negotiableLabel:     { en:'Price is negotiable', fr:'Le prix est négociable', pt:'Preço negociável', ar:'السعر قابل للتفاوض', sw:'Bei inaweza kujadiliwa', zh:'价格可议', hi:'कीमत बातचीत योग्य है', id:'Harga dapat dinegosiasi', bn:'মূল্য আলোচনাযোগ্য', ur:'قیمت قابل گفت و شنید', ja:'価格は交渉可能', ko:'가격 협상 가능' },
  locationLabel:       { en:'Location', fr:'Emplacement', pt:'Localização', ar:'الموقع', sw:'Mahali', zh:'位置', hi:'स्थान', id:'Lokasi', bn:'অবস্থান', ur:'مقام', ja:'場所', ko:'위치' },
  selectCategory:      { en:'Select Category', fr:'Choisir une catégorie', pt:'Selecionar categoria', ar:'اختر الفئة', sw:'Chagua Kundi', zh:'选择分类', hi:'श्रेणी चुनें', id:'Pilih Kategori', bn:'বিভাগ নির্বাচন করুন', ur:'زمرہ منتخب کریں', ja:'カテゴリを選択', ko:'카테고리 선택' },
  selectSubcategory:   { en:'Select Subcategory', fr:'Choisir une sous-catégorie', pt:'Selecionar subcategoria', ar:'اختر الفئة الفرعية', sw:'Chagua Kikundi Kidogo', zh:'选择子分类', hi:'उपश्रेणी चुनें', id:'Pilih Subkategori', bn:'উপবিভাগ নির্বাচন করুন', ur:'ذیلی زمرہ منتخب کریں', ja:'サブカテゴリを選択', ko:'하위 카테고리 선택' },
  conditionNew:        { en:'New', fr:'Neuf', pt:'Novo', ar:'جديد', sw:'Mpya', zh:'全新', hi:'नया', id:'Baru', bn:'নতুন', ur:'نیا', ja:'新品', ko:'새것' },
  conditionUsed:       { en:'Used', fr:'Usagé', pt:'Usado', ar:'مستعمل', sw:'Iliyotumika', zh:'二手', hi:'इस्तेमाल किया', id:'Bekas', bn:'ব্যবহৃত', ur:'استعمال شدہ', ja:'中古', ko:'중고' },
  submitListing:       { en:'Submit Listing', fr:'Soumettre l\'annonce', pt:'Enviar anúncio', ar:'إرسال الإعلان', sw:'Wasilisha Tangazo', zh:'提交商品', hi:'लिस्टिंग सबमिट करें', id:'Kirim Listing', bn:'তালিকা জমা দিন', ur:'فہرست جمع کروائیں', ja:'リストを送信', ko:'목록 제출' },
  updateListingBtn:    { en:'Update Listing', fr:'Mettre à jour l\'annonce', pt:'Atualizar anúncio', ar:'تحديث الإعلان', sw:'Sasisha Tangazo', zh:'更新商品', hi:'लिस्टिंग अपडेट करें', id:'Perbarui Listing', bn:'তালিকা আপডেট করুন', ur:'فہرست اپ ڈیٹ کریں', ja:'リストを更新', ko:'목록 업데이트' },
  imagesUploading:     { en:'Uploading images…', fr:'Chargement des images…', pt:'Enviando imagens…', ar:'جارٍ رفع الصور…', sw:'Inapakia picha…', zh:'正在上传图片…', hi:'छवियाँ अपलोड हो रही हैं…', id:'Mengunggah gambar…', bn:'ছবি আপলোড হচ্ছে…', ur:'تصاویر اپ لوڈ ہو رہی ہیں…', ja:'画像をアップロード中…', ko:'이미지 업로드 중…' },

  // ── Report ────────────────────────────────────────────────────────────────────
  reportTitle:         { en:'Report Listing', fr:'Signaler l\'annonce', pt:'Denunciar anúncio', ar:'الإبلاغ عن إعلان', sw:'Ripoti Tangazo', zh:'举报商品', hi:'लिस्टिंग की रिपोर्ट करें', id:'Laporkan Listing', bn:'তালিকা রিপোর্ট', ur:'فہرست رپورٹ', ja:'リストを報告', ko:'목록 신고' },
  reportReason:        { en:'Reason', fr:'Raison', pt:'Motivo', ar:'السبب', sw:'Sababu', zh:'原因', hi:'कारण', id:'Alasan', bn:'কারণ', ur:'وجہ', ja:'理由', ko:'이유' },
  reportDetails:       { en:'Additional details (optional)', fr:'Détails supplémentaires (facultatif)', pt:'Detalhes adicionais (opcional)', ar:'تفاصيل إضافية (اختياري)', sw:'Maelezo ya ziada (si lazima)', zh:'附加详情（可选）', hi:'अतिरिक्त विवरण (वैकल्पिक)', id:'Detail tambahan (opsional)', bn:'অতিরিক্ত বিবরণ (ঐচ্ছিক)', ur:'اضافی تفصیلات (اختیاری)', ja:'追加詳細（任意）', ko:'추가 세부 정보 (선택 사항)' },
  reportSubmitted:     { en:'Report submitted. Thank you.', fr:'Signalement envoyé. Merci.', pt:'Denúncia enviada. Obrigado.', ar:'تم الإبلاغ. شكراً لك.', sw:'Ripoti imetumwa. Asante.', zh:'举报已提交，谢谢。', hi:'रिपोर्ट सबमिट की गई। धन्यवाद।', id:'Laporan dikirim. Terima kasih.', bn:'রিপোর্ট জমা হয়েছে। ধন্যবাদ।', ur:'رپورٹ جمع ہو گئی۔ شکریہ۔', ja:'報告を送信しました。ありがとうございます。', ko:'신고가 제출되었습니다. 감사합니다.' },
  submitReport:        { en:'Submit Report', fr:'Envoyer le signalement', pt:'Enviar denúncia', ar:'إرسال البلاغ', sw:'Tuma Ripoti', zh:'提交举报', hi:'रिपोर्ट सबमिट करें', id:'Kirim Laporan', bn:'রিপোর্ট জমা দিন', ur:'رپورٹ جمع کروائیں', ja:'報告を送信', ko:'신고 제출' },
  reasonFake:          { en:'Fake or misleading listing', fr:'Annonce fausse ou trompeuse', pt:'Anúncio falso ou enganoso', ar:'إعلان مزيف أو مضلل', sw:'Tangazo la uongo au linalochanganya', zh:'虚假或误导性商品', hi:'नकली या भ्रामक लिस्टिंग', id:'Listing palsu atau menyesatkan', bn:'ভুয়া বা বিভ্রান্তিকর তালিকা', ur:'جعلی یا گمراہ کن فہرست', ja:'偽または誤解を招くリスト', ko:'가짜 또는 오해의 소지가 있는 목록' },
  reasonScam:          { en:'Suspected scam', fr:'Arnaque suspectée', pt:'Suspeita de golpe', ar:'احتيال مشتبه به', sw:'Ulaghai unaoshukiwa', zh:'疑似诈骗', hi:'संदिग्ध घोटाला', id:'Dugaan penipuan', bn:'সন্দেহজনক প্রতারণা', ur:'مشتبہ دھوکہ', ja:'詐欺の疑い', ko:'사기 의심' },
  reasonInappropriate: { en:'Inappropriate content', fr:'Contenu inapproprié', pt:'Conteúdo inadequado', ar:'محتوى غير مناسب', sw:'Maudhui yasiyofaa', zh:'不当内容', hi:'अनुचित सामग्री', id:'Konten tidak pantas', bn:'অনুপযুক্ত বিষয়বস্তু', ur:'نامناسب مواد', ja:'不適切なコンテンツ', ko:'부적절한 콘텐츠' },
  reasonWrong:         { en:'Wrong category', fr:'Mauvaise catégorie', pt:'Categoria errada', ar:'فئة خاطئة', sw:'Kundi lisilo sahihi', zh:'分类错误', hi:'गलत श्रेणी', id:'Kategori salah', bn:'ভুল বিভাগ', ur:'غلط زمرہ', ja:'間違ったカテゴリ', ko:'잘못된 카테고리' },
  reasonOther:         { en:'Other', fr:'Autre', pt:'Outro', ar:'أخرى', sw:'Nyingine', zh:'其他', hi:'अन्य', id:'Lainnya', bn:'অন্যান্য', ur:'دیگر', ja:'その他', ko:'기타' },

  // ── Promote ───────────────────────────────────────────────────────────────────
  promoteListing:      { en:'Promote Listing', fr:'Promouvoir l\'annonce', pt:'Promover anúncio', ar:'ترويج الإعلان', sw:'Tangaza Orodha', zh:'推广商品', hi:'लिस्टिंग प्रमोट करें', id:'Promosikan Listing', bn:'তালিকা প্রমোট করুন', ur:'فہرست فروغ دیں', ja:'リストをプロモート', ko:'목록 홍보' },
  promoteTypeSponsored:{ en:'Sponsored (Featured listing)', fr:'Sponsorisé (annonce en vedette)', pt:'Patrocinado (anúncio em destaque)', ar:'ممول (إعلان مميز)', sw:'Iliyosponsor (tangazo la kuonyeshwa)', zh:'赞助（精选商品）', hi:'प्रायोजित (फ़ीचर्ड लिस्टिंग)', id:'Disponsori (listing unggulan)', bn:'স্পনসর করা (ফিচার্ড তালিকা)', ur:'سپانسر شدہ (نمایاں فہرست)', ja:'スポンサー（注目リスト）', ko:'스폰서 (추천 목록)' },
  promoteTypeFlash:    { en:'Flash Sale (time-limited discount)', fr:'Vente Flash (remise limitée dans le temps)', pt:'Flash Sale (desconto por tempo limitado)', ar:'عرض خاطف (خصم محدود الوقت)', sw:'Mauzo ya Haraka (punguzo la muda)', zh:'闪购（限时折扣）', hi:'फ्लैश सेल (सीमित समय छूट)', id:'Flash Sale (diskon terbatas waktu)', bn:'ফ্ল্যাশ সেল (সীমিত সময়ের ছাড়)', ur:'فلیش سیل (محدود وقت کی چھوٹ)', ja:'フラッシュセール（期間限定割引）', ko:'플래시 세일 (기간 한정 할인)' },
  promoteDays:         { en:'Duration (days)', fr:'Durée (jours)', pt:'Duração (dias)', ar:'المدة (أيام)', sw:'Muda (siku)', zh:'时长（天）', hi:'अवधि (दिन)', id:'Durasi (hari)', bn:'সময়কাল (দিন)', ur:'مدت (دن)', ja:'期間（日数）', ko:'기간 (일)' },
  promotePayment:      { en:'Payment Method', fr:'Méthode de paiement', pt:'Método de pagamento', ar:'طريقة الدفع', sw:'Njia ya Malipo', zh:'支付方式', hi:'भुगतान विधि', id:'Metode Pembayaran', bn:'পেমেন্ট পদ্ধতি', ur:'ادائیگی کا طریقہ', ja:'支払い方法', ko:'결제 방법' },
  promoteRef:          { en:'Transaction Reference', fr:'Référence de transaction', pt:'Referência da transação', ar:'مرجع المعاملة', sw:'Kumbukumbu ya Muamala', zh:'交易参考号', hi:'लेनदेन संदर्भ', id:'Referensi Transaksi', bn:'লেনদেন রেফারেন্স', ur:'لین دین حوالہ', ja:'取引参照', ko:'거래 참조' },
  promoteSubmitted:    { en:'Promotion request submitted!', fr:'Demande de promotion envoyée !', pt:'Solicitação de promoção enviada!', ar:'تم إرسال طلب الترويج!', sw:'Ombi la uendelezaji limetumwa!', zh:'推广申请已提交！', hi:'प्रमोशन अनुरोध सबमिट किया गया!', id:'Permintaan promosi dikirim!', bn:'প্রচার অনুরোধ জমা হয়েছে!', ur:'فروغ کی درخواست جمع ہو گئی!', ja:'プロモーションリクエストを送信しました！', ko:'홍보 요청이 제출되었습니다!' },

  // ── Misc fixes ────────────────────────────────────────────────────────────────
  reviewSubmittedTitle: { en:'Review submitted!', fr:'Avis soumis !', pt:'Avaliação enviada!', ar:'تم إرسال التقييم!', sw:'Tathmini imetumwa!', zh:'评价已提交！', hi:'समीक्षा सबमिट की गई!', id:'Ulasan dikirim!', bn:'রিভিউ জমা হয়েছে!', ur:'جائزہ جمع ہو گیا!', ja:'レビューを送信しました！', ko:'리뷰가 제출되었습니다!' },
  reviewPendingNote:    { en:'Your review is awaiting approval and will appear shortly.', fr:"Votre avis est en attente d'approbation.", pt:'Sua avaliação aguarda aprovação.', ar:'مراجعتك قيد الموافقة.', sw:'Tathmini yako inasubiri idhini.', zh:'您的评价正在等待审核，稍后将显示。', hi:'आपकी समीक्षा अनुमोदन की प्रतीक्षा में है।', id:'Ulasan Anda menunggu persetujuan.', bn:'আপনার রিভিউ অনুমোদনের অপেক্ষায় আছে।', ur:'آپ کا جائزہ منظوری کا انتظار کر رہا ہے۔', ja:'レビューは承認待ちです。', ko:'귀하의 리뷰는 승인을 기다리고 있습니다.' },
  loadMore:             { en:'Load More', fr:'Charger plus', pt:'Carregar mais', ar:'تحميل المزيد', sw:'Pakia Zaidi', zh:'加载更多', hi:'अधिक लोड करें', id:'Muat Lebih Banyak', bn:'আরও লোড করুন', ur:'مزید لوڈ کریں', ja:'さらに読み込む', ko:'더 보기' },
  noMoreListings:       { en:'No more listings', fr:'Plus d\'annonces', pt:'Sem mais anúncios', ar:'لا توجد المزيد من الإعلانات', sw:'Hakuna matangazo zaidi', zh:'没有更多商品了', hi:'और कोई लिस्टिंग नहीं', id:'Tidak ada listing lagi', bn:'আর কোনো তালিকা নেই', ur:'مزید فہرستیں نہیں', ja:'リストはこれ以上ありません', ko:'더 이상 목록이 없습니다' },
  messageSentDesc:      { en:'The seller will reply in your messages inbox.', fr:'Le vendeur répondra dans votre boîte de messages.', pt:'O vendedor responderá na sua caixa de mensagens.', ar:'سيرد البائع في صندوق رسائلك.', sw:'Muuzaji atajibu katika kisanduku chako cha ujumbe.', zh:'卖家将在您的消息收件箱中回复。', hi:'विक्रेता आपके संदेश इनबॉक्स में जवाब देगा।', id:'Penjual akan membalas di kotak masuk pesan Anda.', bn:'বিক্রেতা আপনার বার্তা ইনবক্সে উত্তর দেবে।', ur:'بائع آپ کے پیغام ان باکس میں جواب دے گا۔', ja:'出品者はメッセージ受信トレイで返信します。', ko:'판매자가 메시지 받은 편지함에서 답장할 것입니다.' },
  viewMessages:         { en:'View Messages', fr:'Voir les messages', pt:'Ver mensagens', ar:'عرض الرسائل', sw:'Tazama Ujumbe', zh:'查看消息', hi:'संदेश देखें', id:'Lihat Pesan', bn:'বার্তা দেখुन', ur:'پیغامات دیکھیں', ja:'メッセージを見る', ko:'메시지 보기' },
};

export function translate(key: string, lang: string): string {
  const map = T[key];
  if (!map) return key;
  return t(map, lang);
}

export function getDir(lang: string): 'ltr' | 'rtl' {
  return RTL_LANGS.has(lang) ? 'rtl' : 'ltr';
}
